function result = AnalyzeBestQuickPopulationOutliers_LSQOD(options)
%ANALYZEBESTQUICKPOPULATIONOUTLIERS_LSQOD Analyze LSQ-OD population influence.

arguments
    options.OutputFolder (1, 1) string = ...
        "C:\EM\StimTuningAnalysis\BestCorrelationChannelPopulation_LSQOD\OutlierAnalysis_SelectedChannelCriteria"
    options.TopCountPerUnitType (1, 1) double ...
        {mustBeInteger, mustBePositive} = 5
    options.FigureVisible (1, 1) logical = false
end

root = "C:\EM\StimTuningAnalysis\BestCorrelationChannelPopulation_LSQOD";
result = AnalyzeBestQuickPopulationOutliers( ...
    PopulationResultFile=fullfile(root, "PopulationAnalysisResults.mat"), ...
    PreparedInputFile=fullfile(root, ...
    "unit_table_gof_best_quick_channel.mat"), ...
    OutputFolder=options.OutputFolder, ...
    TopCountPerUnitType=options.TopCountPerUnitType, ...
    FigureVisible=options.FigureVisible);
end
