function analysis = ...
    RunPopulationAnalysis_GaussianAllChannelMeta_AdjacentAICleanup(options)
%RUNPOPULATIONANALYSIS_GAUSSIANALLCHANNELMETA_ADJACENTAICLEANUP
% Fit one Gaussian distance profile, build an all-live-channel Quick meta
% tuning, and compare the population before and after four-neighbor
% combined-AI continuity cleanup.
%
% The shared Gaussian sigma is selected using the established Jim MT 2D
% combined-cue analysis:
%
%   DeltaBias_combined ~ Gaussian-meta combined-cue AI
%
% with repeated session-grouped cross-validation. The filtered cohort is
% also evaluated at the full-cohort sigma before sigma is refit, separating
% the effect of site removal from the effect of retuning the profile.
%
% For the final population analysis, every available live channel is
% z-scored across all valid Quick trials. AI is calculated from the
% Gaussian-weighted z-scored meta response. Eye dominance and 2D/3D class
% are recalculated from the matching Gaussian-weighted raw-FR meta curve.

arguments
    options.StateFile (1, 1) string = ...
        "C:\EM\PopulationAnalysis\unit_table_gof.mat"
    options.NeuroAllFile (1, 1) string = [ ...
        "P:\Codes\Matlab\offlineAnalysis\3DMotionAnalysis\" + ...
        "Stimulation\John_analysis_try\Clustering\NeuroAll_20250627.mat"]
    options.OutputFolder (1, 1) string = [ ...
        "C:\EM\StimTuningAnalysis\" + ...
        "GaussianAllChannelMeta_Adjacent4AIContinuity"]
    options.Areas (1, :) string = ["MT", "FST"]
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.TuningAlpha (1, 1) double ...
        {mustBeGreaterThan(options.TuningAlpha, 0), ...
        mustBeLessThan(options.TuningAlpha, 1)} = 0.05
    options.SigmaValues (1, :) double = logspace(-2, 2, 41)
    options.NumRepeats (1, 1) double ...
        {mustBeInteger, mustBePositive} = 5
    options.NumFolds (1, 1) double ...
        {mustBeInteger, mustBeGreaterThan(options.NumFolds, 1)} = 5
    options.RandomSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 1
    options.FigureVisible (1, 1) logical = false
    options.JimCacheFolder (1, 1) string = "C:\Jim\StimData"
    options.ClayCacheFolder (1, 1) string = "C:\Clay\StimData"
end

if ~isfile(options.StateFile)
    error('GaussianMetaCleanup:MissingStateFile', ...
        'Input MAT file does not exist: %s', options.StateFile);
end
if ~isfile(options.NeuroAllFile)
    error('GaussianMetaCleanup:MissingNeuroAll', ...
        'NeuroAll input does not exist: %s', options.NeuroAllFile);
end
ensureFolder(options.OutputFolder);
scriptFolder = string(fileparts(mfilename('fullpath')));
projectFolder = string(fileparts(scriptFolder));
addpath(scriptFolder, fullfile(scriptFolder, 'common'), ...
    fullfile(projectFolder, 'PopulationAnalysis'));

[unitTable, resolvedStateFile, workbookAudit] = ...
    LoadLatestUnitTableGof(options.StateFile);
audit = AuditAdjacentQuickChannelAIFlips(unitTable, ...
    JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder, ...
    TuningAlpha=options.TuningAlpha, NeighborRadius=2, ...
    CandidateMask=true(height(unitTable), 1));
excludedRows = audit.TableRow(audit.ExcludeForAIFlip & ...
    audit.Status == "Success");
writetable(audit, fullfile(options.OutputFolder, ...
    'Adjacent4ChannelCombinedAIAudit.csv'));
writetable(audit(ismember(audit.TableRow, excludedRows), :), ...
    fullfile(options.OutputFolder, 'DiscontinuousSessionsRemoved.csv'));

paths = struct('unitTableGof', char(resolvedStateFile), ...
    'neuroAll', char(options.NeuroAllFile));
fitOptions = namedargs2cell(struct( ...
    'NumRepeats', options.NumRepeats, ...
    'NumFolds', options.NumFolds, ...
    'RandomSeed', options.RandomSeed, ...
    'SigmaValues', options.SigmaValues));
fullFit = currentSpreadCombinedCueGaussianSigmaR2( ...
    paths, "gaussian-fr", fitOptions{:});
filteredFit = currentSpreadCombinedCueGaussianSigmaR2( ...
    paths, "gaussian-fr", fitOptions{:}, ...
    ExcludedOriginalRows=excludedRows);
if ~isfinite(fullFit.bestSigma) || ~isfinite(filteredFit.bestSigma)
    error('GaussianMetaCleanup:NoFiniteSigma', ...
        'The full or continuity-filtered fit did not yield a finite sigma.');
end

[~, fullSigmaIndexInFiltered] = min(abs( ...
    filteredFit.sigmaValues - fullFit.bestSigma));
sigmaComparison = buildSigmaComparison( ...
    fullFit, filteredFit, fullSigmaIndexInFiltered);
writetable(sigmaComparison, fullfile(options.OutputFolder, ...
    'GaussianSigmaComparison.csv'));
writetable(tagSigmaCurve(fullFit.table, "Full cohort"), ...
    fullfile(options.OutputFolder, 'GaussianSigmaCurve_Full.csv'));
writetable(tagSigmaCurve(filteredFit.table, ...
    "Four-neighbor continuity filtered"), ...
    fullfile(options.OutputFolder, 'GaussianSigmaCurve_Filtered.csv'));

previousVisibility = get(groot, 'defaultFigureVisible');
visibilityCleanup = onCleanup( ...
    @() set(groot, 'defaultFigureVisible', previousVisibility));
set(groot, 'defaultFigureVisible', ternary( ...
    options.FigureVisible, 'on', 'off'));
figureHandles = saveGaussianComparisonFigures( ...
    fullFit, filteredFit, options.OutputFolder);
close(figureHandles(isgraphics(figureHandles)));

commonPopulationOptions = struct( ...
    'StateFile', resolvedStateFile, ...
    'Areas', options.Areas, ...
    'Monkey', options.Monkey, ...
    'FigureVisible', options.FigureVisible, ...
    'JimCacheFolder', options.JimCacheFolder, ...
    'ClayCacheFolder', options.ClayCacheFolder, ...
    'WeightingMode', "GaussianAll");

fullFolder = fullfile(options.OutputFolder, ...
    '01_FullCohort_FullFitSigma');
filteredFixedFolder = fullfile(options.OutputFolder, ...
    '02_FilteredCohort_FullFitSigma');
filteredRefitFolder = fullfile(options.OutputFolder, ...
    '03_FilteredCohort_RefitSigma');

fullPopulation = runPopulation(commonPopulationOptions, fullFolder, ...
    fullFit.bestSigma, zeros(0, 1));
filteredFixedPopulation = runPopulation(commonPopulationOptions, ...
    filteredFixedFolder, fullFit.bestSigma, excludedRows);
filteredRefitPopulation = runPopulation(commonPopulationOptions, ...
    filteredRefitFolder, filteredFit.bestSigma, excludedRows);
clear visibilityCleanup

audit.PopulationCandidate = fullPopulation.CandidateMask;
audit.RemovedPopulationCandidate = audit.ExcludeForAIFlip & ...
    audit.PopulationCandidate;
audit.GaussianFitReferenceCandidate = ismember( ...
    audit.TableRow, fullFit.baseOriginalRowIndex);
audit.RemovedGaussianFitReferenceCandidate = audit.ExcludeForAIFlip & ...
    audit.GaussianFitReferenceCandidate;
writetable(audit, fullfile(options.OutputFolder, ...
    'Adjacent4ChannelCombinedAIAudit.csv'));
writetable(audit(audit.ExcludeForAIFlip, :), ...
    fullfile(options.OutputFolder, 'DiscontinuousSessionsRemoved.csv'));
writetable(audit(audit.RemovedPopulationCandidate, :), ...
    fullfile(options.OutputFolder, ...
    'DiscontinuousPopulationCandidatesRemoved.csv'));
writetable(audit(audit.RemovedGaussianFitReferenceCandidate, :), ...
    fullfile(options.OutputFolder, ...
    'DiscontinuousGaussianFitSessionsRemoved.csv'));

modelComparison = [ ...
    tagPopulationSummary(fullPopulation.ModelSummaryComparison, ...
    "Full cohort", "Full-cohort fitted sigma", fullFit.bestSigma); ...
    tagPopulationSummary(filteredFixedPopulation.ModelSummaryComparison, ...
    "Continuity filtered", "Full-cohort fitted sigma", ...
    fullFit.bestSigma); ...
    tagPopulationSummary(filteredRefitPopulation.ModelSummaryComparison, ...
    "Continuity filtered", "Filtered-cohort refitted sigma", ...
    filteredFit.bestSigma)];
modelComparison = modelComparison(contains( ...
    modelComparison.Readout, "Gaussian"), :);
writetable(modelComparison, fullfile(options.OutputFolder, ...
    'PopulationModelSummary_GaussianMetaComparison.csv'));

flowComparison = [ ...
    tagPopulationFlow(fullPopulation.PopulationCohortFlow, ...
    "Full cohort", fullFit.bestSigma); ...
    tagPopulationFlow(filteredFixedPopulation.PopulationCohortFlow, ...
    "Continuity filtered; fixed full sigma", fullFit.bestSigma); ...
    tagPopulationFlow(filteredRefitPopulation.PopulationCohortFlow, ...
    "Continuity filtered; refit sigma", filteredFit.bestSigma)];
writetable(flowComparison, fullfile(options.OutputFolder, ...
    'PopulationCohortFlow_GaussianMetaComparison.csv'));

analysis = struct();
analysis.StateFile = resolvedStateFile;
analysis.NeuroAllFile = options.NeuroAllFile;
analysis.OutputFolder = options.OutputFolder;
analysis.ContinuityRule = sprintf([ ...
    'Remove a site when any of physical neighbors -2,-1,+1,+2 has ' ...
    'combined-cue p < %.6g and combined-cue AI sign opposite to the ' ...
    'stimulation channel.'], options.TuningAlpha);
analysis.AdjacentAudit = audit;
analysis.ExcludedOriginalRows = excludedRows;
analysis.FullFit = fullFit;
analysis.FilteredFit = filteredFit;
analysis.SigmaComparison = sigmaComparison;
analysis.FullPopulation = fullPopulation;
analysis.FilteredFixedSigmaPopulation = filteredFixedPopulation;
analysis.FilteredRefitPopulation = filteredRefitPopulation;
analysis.PopulationModelSummaryComparison = modelComparison;
analysis.PopulationCohortFlowComparison = flowComparison;
analysis.MetaDefinition = [ ...
    "All available live channels; one Gaussian distance profile shared across sessions"; ...
    "Each channel z-scored across all valid Quick trials before weighted summation"; ...
    "AI from z-scored meta curve"; ...
    "Dominant eye and 2D/3D assignment from matching raw-FR meta curve"];
analysis.SigmaFitReferenceCohort = [ ...
    "Established combined-cue Gaussian-FR fit"; ...
    "Jim MT sessions labeled 2D in the source table"; ...
    "DeltaBias_combined ~ AI with repeated session-grouped five-fold CV"];
analysis.WorkbookAudit = workbookAudit;
population_analysis = analysis;
save(fullfile(options.OutputFolder, ...
    'GaussianAllChannelMeta_AdjacentAICleanupResults.mat'), ...
    'population_analysis', '-v7.3');

fprintf(['Gaussian all-channel continuity comparison complete. ' ...
    'Removed %d sessions. Full sigma %.6g; filtered refit sigma %.6g. ' ...
    'Outputs: %s\n'], numel(excludedRows), fullFit.bestSigma, ...
    filteredFit.bestSigma, options.OutputFolder);
end


function result = runPopulation(commonOptions, outputFolder, sigma, excluded)
argsCell = namedargs2cell(commonOptions);
result = RunPopulationAnalysis_EqualFiveChannelMetaTuning( ...
    argsCell{:}, OutputFolder=outputFolder, GaussianSigma=sigma, ...
    ExcludedOriginalRows=excluded);
end


function output = buildSigmaComparison(fullFit, filteredFit, fixedIndex)
cohort = ["Full cohort"; "Continuity filtered"; "Continuity filtered"];
sigmaSource = ["Fitted within cohort"; "Fixed from full cohort"; ...
    "Refitted within filtered cohort"];
sigma = [fullFit.bestSigma; fullFit.bestSigma; filteredFit.bestSigma];
curveIndex = [fullFit.bestIndex; fixedIndex; filteredFit.bestIndex];
sessionCount = [fullFit.sessionCount; filteredFit.sessionCount; ...
    filteredFit.sessionCount];
meanCVR2 = [fullFit.meanR2(fullFit.bestIndex); ...
    filteredFit.meanR2(fixedIndex); ...
    filteredFit.meanR2(filteredFit.bestIndex)];
semCVR2 = [fullFit.semR2(fullFit.bestIndex); ...
    filteredFit.semR2(fixedIndex); ...
    filteredFit.semR2(filteredFit.bestIndex)];
effectiveChannels = [fullFit.effectiveChannels(fullFit.bestIndex); ...
    filteredFit.effectiveChannels(fixedIndex); ...
    filteredFit.effectiveChannels(filteredFit.bestIndex)];
descriptive = [descriptiveCombinedCueFit(fullFit, fullFit.bestIndex); ...
    descriptiveCombinedCueFit(filteredFit, fixedIndex); ...
    descriptiveCombinedCueFit(filteredFit, filteredFit.bestIndex)];
output = table(cohort, sigmaSource, sigma, curveIndex, sessionCount, ...
    effectiveChannels, meanCVR2, semCVR2, descriptive.N, ...
    descriptive.Intercept, descriptive.Slope, descriptive.P_AI, ...
    descriptive.R2, 'VariableNames', {'Cohort', 'SigmaSource', 'Sigma', ...
    'SigmaGridIndex', 'NSessions', 'EffectiveChannels', 'MeanCVR2', ...
    'SEMCVR2', 'NDescriptive', 'Intercept', 'Slope', 'P_AI', ...
    'DescriptiveR2'});
end


function output = descriptiveCombinedCueFit(result, sigmaIndex)
x = result.weightedAIBySigma(:, sigmaIndex);
y = result.behavior;
valid = isfinite(x) & isfinite(y);
output = table(nnz(valid), NaN, NaN, NaN, NaN, ...
    'VariableNames', {'N', 'Intercept', 'Slope', 'P_AI', 'R2'});
if nnz(valid) < 3 || std(x(valid)) <= eps
    return
end
model = fitlm(x(valid), y(valid));
output.Intercept = model.Coefficients.Estimate(1);
output.Slope = model.Coefficients.Estimate(2);
output.P_AI = model.Coefficients.pValue(2);
output.R2 = model.Rsquared.Ordinary;
end


function output = tagSigmaCurve(input, cohort)
output = input;
output.Cohort = repmat(cohort, height(output), 1);
output = movevars(output, 'Cohort', 'Before', 1);
end


function output = tagPopulationSummary(input, cohort, sigmaSource, sigma)
output = input;
output.Cohort = repmat(cohort, height(output), 1);
output.SigmaSource = repmat(sigmaSource, height(output), 1);
output.GaussianSigma = repmat(sigma, height(output), 1);
output = movevars(output, {'Cohort', 'SigmaSource', 'GaussianSigma'}, ...
    'Before', 1);
end


function output = tagPopulationFlow(input, cohort, sigma)
output = input;
output.Cohort = repmat(cohort, height(output), 1);
output.GaussianSigma = repmat(sigma, height(output), 1);
output = movevars(output, {'Cohort', 'GaussianSigma'}, 'Before', 1);
end


function handles = saveGaussianComparisonFigures(fullFit, filteredFit, folder)
handles = gobjects(2, 1);
handles(1) = figure('Color', 'w', 'Position', [100 100 920 620]);
hold on
errorbar(fullFit.sigmaValues, fullFit.meanR2, fullFit.semR2, ...
    'o-', 'LineWidth', 1.5, 'MarkerSize', 4, ...
    'DisplayName', sprintf('Full (n=%d)', fullFit.sessionCount));
errorbar(filteredFit.sigmaValues, filteredFit.meanR2, filteredFit.semR2, ...
    'o-', 'LineWidth', 1.5, 'MarkerSize', 4, ...
    'DisplayName', sprintf('Filtered (n=%d)', filteredFit.sessionCount));
xline(fullFit.bestSigma, '--', 'Full best', 'HandleVisibility', 'off');
xline(filteredFit.bestSigma, '--', 'Filtered best', ...
    'HandleVisibility', 'off');
set(gca, 'XScale', 'log'); grid on; box off
xlabel('Shared Gaussian sigma (physical contact spacings)');
ylabel('Repeated 5-fold cross-validated R^2');
title('Combined-cue Gaussian meta fit before and after continuity cleanup');
legend('Location', 'best');
exportgraphics(handles(1), fullfile(folder, ...
    'GaussianSigmaCVR2_FullVsFiltered.png'), 'Resolution', 300);
savefig(handles(1), fullfile(folder, ...
    'GaussianSigmaCVR2_FullVsFiltered.fig'));

handles(2) = figure('Color', 'w', 'Position', [120 120 920 620]);
plot(fullFit.positionOffset, fullFit.bestWeights, 'o-', ...
    'LineWidth', 2, 'DisplayName', ...
    sprintf('Full best, sigma %.4g', fullFit.bestSigma));
hold on
plot(filteredFit.positionOffset, filteredFit.bestWeights, 'o-', ...
    'LineWidth', 2, 'DisplayName', ...
    sprintf('Filtered best, sigma %.4g', filteredFit.bestSigma));
grid on; box off
xlabel('Physical channel position relative to stimulation contact');
ylabel('Nominal normalized Gaussian weight');
title('Shared all-channel Gaussian profiles');
legend('Location', 'best');
exportgraphics(handles(2), fullfile(folder, ...
    'GaussianProfiles_FullVsFiltered.png'), 'Resolution', 300);
savefig(handles(2), fullfile(folder, ...
    'GaussianProfiles_FullVsFiltered.fig'));
end


function ensureFolder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end


function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
