function analysis = RunPopulationAnalysis_BestQuickChannels_LSQOD(options)
%RUNPOPULATIONANALYSIS_BESTQUICKCHANNELS_LSQOD Run the LSQ-OD version.
%
% For each selected 3D Quick channel, MonoL and MonoR are compared with the
% Combined tuning using sums of squared errors. The lower-error eye is the
% dominant eye. Only the normalized absolute LSQ difference enters models
% and plots; sign is retained internally only for eye assignment.

arguments
    options.StateFile (1, 1) string = ...
        "C:\EM\StimTuningAnalysis\unit_table_stim.mat"
    options.OutputFolder (1, 1) string = ...
        "C:\EM\StimTuningAnalysis\BestCorrelationChannelPopulation_LSQOD"
    options.Area (1, 1) string ...
        {mustBeMember(options.Area, ["MT", "FST"])} = "FST"
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.MakeRankingPlots (1, 1) logical = false
    options.FigureVisible (1, 1) logical = false
    options.MaxAbsRelativePosition (1, 1) double ...
        {mustBeNonnegative, mustBeInteger} = 4
    options.JimCacheFolder (1, 1) string = "C:\Jim\StimData"
    options.ClayCacheFolder (1, 1) string = "C:\Clay\StimData"
end

analysis = RunPopulationAnalysis_BestQuickChannels( ...
    StateFile=options.StateFile, OutputFolder=options.OutputFolder, ...
    Area=options.Area, Monkey=options.Monkey, ODMethod="LSQ", ...
    MaxAbsRelativePosition=options.MaxAbsRelativePosition, ...
    MakeRankingPlots=options.MakeRankingPlots, ...
    FigureVisible=options.FigureVisible, ...
    JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder);

comparison = methodODAudit( ...
    analysis.Correlation.best_quick_selection_audit, "Correlation");
writetable(comparison, fullfile(options.OutputFolder, ...
    'LSQ_vs_Max_OD_Audit.csv'));

summary = groupsummary(comparison, 'Method', ...
    {'sum', 'mean'}, {'ODDominanceChangedFromMax', ...
    'SelectedODMagnitudeForModel'});
writetable(summary, fullfile(options.OutputFolder, ...
    'LSQ_vs_Max_OD_Summary.csv'));
analysis.LSQvsMaxODAudit = comparison;
analysis.LSQvsMaxODSummary = summary;
end


function output = methodODAudit(audit, method)
variables = {'ArtifactTableRow', 'BestQuickChannel', ...
    'SelectedODMaxFromQuickTuning', 'SelectedODMaxDominantEye', ...
    'SelectedODLSQSigned', 'SelectedODLSQRaw', ...
    'SelectedSignedODForEyeAssignment', ...
    'SelectedODMagnitudeForModel', 'SelectedODDominantEye', ...
    'LSQLeftError', 'LSQRightError', 'ODDominanceChangedFromMax', ...
    'QuickODSupportCount', 'Status', 'Message'};
output = audit(:, variables);
output.Method = repmat(method, height(output), 1);
output = movevars(output, 'Method', 'Before', 1);
end
