function analysis = ...
    RunPopulationAnalysis_OriginalMaxOD_TwoAdjacentChannels(options)
%RUNPOPULATIONANALYSIS_ORIGINALMAXOD_TWOADJACENTCHANNELS Radius-2 cleanup.
%
% This is the separate two-contacts-per-side version of the original
% stimulation-channel Quick AI / maximum-response OD population analysis.
% It evaluates relative physical probe positions -2, -1, +1, and +2.
% A site is marked and excluded when any live neighbor with significant
% combined-cue direction tuning has combined-cue AI opposite in sign to the
% stimulation channel. The unit-type model specification remains:
%
%   2D: DeltaBias ~ AI for each cue;
%   2D: MergedEyeDeltaBias ~ AI + AI:OD for merged eyes;
%   3D: DeltaBias ~ AI for each cue only.

arguments
    options.StateFile (1, 1) string = ...
        "C:\EM\PopulationAnalysis\unit_table_gof.mat"
    options.OutputFolder (1, 1) string = ...
        ["C:\EM\StimTuningAnalysis\" + ...
        "OriginalMaxOD_Adjacent2EachSide_CombinedAIConsistency_UnitTypeModels"]
    options.Areas (1, :) string = ["MT", "FST"]
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.TuningAlpha (1, 1) double ...
        {mustBeGreaterThan(options.TuningAlpha, 0), ...
        mustBeLessThan(options.TuningAlpha, 1)} = 0.05
    options.FigureVisible (1, 1) logical = false
    options.JimCacheFolder (1, 1) string = "C:\Jim\StimData"
    options.ClayCacheFolder (1, 1) string = "C:\Clay\StimData"
end

analysis = RunPopulationAnalysis_OriginalMaxOD_AdjacentAICleanup( ...
    StateFile=options.StateFile, ...
    OutputFolder=options.OutputFolder, ...
    Areas=options.Areas, ...
    Monkey=options.Monkey, ...
    TuningAlpha=options.TuningAlpha, ...
    NeighborRadius=2, ...
    FigureVisible=options.FigureVisible, ...
    JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder);
end
