function analysis = ...
    RunPopulationAnalysis_OriginalLSQOD_TwoAdjacentChannels(options)
%RUNPOPULATIONANALYSIS_ORIGINALLSQOD_TWOADJACENTCHANNELS LSQ-OD radius-2 run.
%
% Keep 3DMotionQuick AI fixed at the stimulation channel, calculate LSQ OD
% from that channel's Quick tuning, and exclude sessions failing the same
% five-channel (-2,-1,StimElec,+1,+2) combined-AI continuity rule as the
% current maximum-response-OD analysis.

arguments
    options.StateFile (1, 1) string = ...
        "C:\EM\PopulationAnalysis\unit_table_gof.mat"
    options.OutputFolder (1, 1) string = ...
        ["C:\EM\StimTuningAnalysis\" + ...
        "OriginalLSQOD_Adjacent2EachSide_CombinedAIConsistency_UnitTypeModels"]
    options.Areas (1, :) string = ["MT", "FST"]
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.TuningAlpha (1, 1) double ...
        {mustBeGreaterThan(options.TuningAlpha, 0), ...
        mustBeLessThan(options.TuningAlpha, 1)} = 0.05
    options.FigureVisible (1, 1) logical = false
    options.JimCacheFolder (1, 1) string = "C:\Jim\StimData"
    options.ClayCacheFolder (1, 1) string = "C:\Clay\StimData"
end

analysis = RunPopulationAnalysis_OriginalMaxOD_AdjacentAICleanup( ...
    StateFile=options.StateFile, ...
    OutputFolder=options.OutputFolder, ...
    Areas=options.Areas, ...
    Monkey=options.Monkey, ...
    TuningAlpha=options.TuningAlpha, ...
    NeighborRadius=2, ...
    ODMethod="LSQ", ...
    FigureVisible=options.FigureVisible, ...
    JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder);
end
