function results = RunUnifiedBestChannelReanalysis(options)
%RUNUNIFIEDBESTCHANNELREANALYSIS Run three analyses plus original comparator.
%
% Main analyses:
%   1. Stim-task NoStim tuning at StimElec
%   2. Best Quick channel across all channels by pooled Pearson r
%   3. Best Quick channel within 200 um by pooled Pearson r
% Comparison:
%   0. Original Quick tuning at StimElec
%
% Every analysis starts from the same unit_table_stim artifact and enters
% one common population function after source-specific AI, Max OD, raw
% MonoL/MonoR p_AI, and Z3D-Z2D have been recomputed.

arguments
    options.StateFile (1, 1) string = ...
        "C:\EM\StimTuningAnalysis\unit_table_stim.mat"
    options.OutputRoot (1, 1) string = ""
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.FigureVisible (1, 1) logical = false
    options.JimCacheFolder (1, 1) string = "C:\Jim\StimData"
    options.ClayCacheFolder (1, 1) string = "C:\Clay\StimData"
end

scriptFolder = string(fileparts(mfilename('fullpath')));
projectFolder = string(fileparts(scriptFolder));
populationFolder = fullfile(projectFolder, 'PopulationAnalysis');
addpath(scriptFolder, populationFolder);
if strlength(options.OutputRoot) == 0
    options.OutputRoot = fullfile( ...
        "C:\EM", "CurrentSpread", ...
        "UnifiedBestChannelReanalysis_MaxOD_20260820");
end
if ~isfile(options.StateFile)
    error('UnifiedBestChannel:MissingStateFile', ...
        'Shared source table does not exist: %s', options.StateFile);
end
makeFolder(options.OutputRoot);
summaryFolder = fullfile(options.OutputRoot, 'summaries');
sessionFolder = fullfile(options.OutputRoot, 'session_level');
figureFolder = fullfile(options.OutputRoot, 'figures');
makeFolder(summaryFolder); makeFolder(sessionFolder); makeFolder(figureFolder);

sourceHashBefore = fileSHA256(options.StateFile);
fileInfo = dir(options.StateFile);
loaded = load(options.StateFile, 'unit_table_stim');
if ~isfield(loaded, 'unit_table_stim') || ~istable(loaded.unit_table_stim)
    error('UnifiedBestChannel:MissingStimTable', ...
        '%s does not contain table unit_table_stim.', options.StateFile);
end
sourceTable = loaded.unit_table_stim;
sourceTable.SourceTableRow = (1:height(sourceTable))';
allChannelLimit = max(double(sourceTable.NChannels), [], 'omitnan') - 1;
if ~isfinite(allChannelLimit) || allChannelLimit < 1
    error('UnifiedBestChannel:InvalidChannelCount', ...
        'Could not determine the all-channel distance limit.');
end

criteriaTable = buildCriteriaTable(options.StateFile, sourceHashBefore, ...
    allChannelLimit);
writetable(criteriaTable, fullfile(summaryFolder, 'UnifiedCriteria.csv'));

fprintf('\n[comparison] Original Quick tuning at the stimulation channel\n');
[originalNormalized, originalDetails] = prepareOriginalQuickAnalysis( ...
    sourceTable, options.OutputRoot, options);

fprintf('\n[1/3] Stim-task NoStim tuning with recomputed source criteria\n');
[stimTable, stimIndexAudit] = ...
    PrepareStimNoStimPopulationAIOD(sourceTable);
[stimTable, stimCriteriaAudit] = ...
    PrepareStimNoStimSelectionCriteria(stimTable);
stimValid = stimIndexAudit.IndexStatus == "Success" & ...
    stimCriteriaAudit.Status == "Success";
stimNormalized = normalizePreparedTable(stimTable, ...
    "Stim-task NoStim", stimTable.stim_noStim_AI, ...
    stimTable.stim_noStim_OD_max, stimValid, ...
    double(stimTable.StimElec), nan(height(stimTable), 1), ...
    zeros(height(stimTable), 1), zeros(height(stimTable), 1), ...
    string(stimIndexAudit.IndexStatus), ...
    string(stimCriteriaAudit.Status), ...
    stimCriteriaAudit.SelectedMonoLP, ...
    stimCriteriaAudit.SelectedMonoRP, false(height(stimTable), 1));
stimDetailFolder = fullfile(options.OutputRoot, '01_StimTask_NoStim');
makeFolder(stimDetailFolder);
writetable(stimIndexAudit, fullfile(stimDetailFolder, ...
    'StimNoStim_AI_OD_Audit.csv'));
writetable(stimCriteriaAudit, fullfile(stimDetailFolder, ...
    'StimNoStim_SelectedSourceCriteriaAudit.csv'));
save(fullfile(stimDetailFolder, 'PreparedPopulationInput.mat'), ...
    'stimNormalized', '-v7.3');

fprintf('\n[2/3] Best Quick channel across all available channels\n');
[quickAllNormalized, quickAllDetails] = prepareQuickAnalysis( ...
    sourceTable, options.StateFile, options.OutputRoot, ...
    "Best Quick - all channels", '02_BestQuick_AllChannels', ...
    allChannelLimit, options);

fprintf('\n[3/3] Best Quick channel within 200 um\n');
[quick200Normalized, quick200Details] = prepareQuickAnalysis( ...
    sourceTable, options.StateFile, options.OutputRoot, ...
    "Best Quick - within 200 um", '03_BestQuick_Within200um', ...
    4, options);

methods = ["Original Quick - stimulation channel", "Stim-task NoStim", ...
    "Best Quick - all channels", "Best Quick - within 200 um"];
folders = ["00_OriginalQuick_StimChannel", "01_StimTask_NoStim", ...
    "02_BestQuick_AllChannels", "03_BestQuick_Within200um"];
normalizedTables = {originalNormalized, stimNormalized, ...
    quickAllNormalized, quick200Normalized};
areas = ["MT", "FST"];
partCount = numel(methods) * numel(areas);
populationSummaryParts = cell(partCount, 1);
aixodSummaryParts = cell(partCount, 1);
runSummaryParts = cell(partCount, 1);
populationResults = struct();
writeIndex = 0;

for methodIndex = 1:numel(methods)
    methodFolder = fullfile(options.OutputRoot, folders(methodIndex));
    for areaIndex = 1:numel(areas)
        writeIndex = writeIndex + 1;
        area = areas(areaIndex);
        areaFolder = fullfile(methodFolder, area);
        makeFolder(areaFolder);
        pop = RunUnifiedPopulationFromPreparedTable( ...
            normalizedTables{methodIndex}, area, options.Monkey, ...
            methods(methodIndex), FigureVisible=options.FigureVisible);
        pop.FigureFiles = savePopulationFigures(pop, areaFolder, ...
            folders(methodIndex), area);
        closeValidFigure(pop.Figure2D);
        closeValidFigure(pop.Figure3D);
        pop.Figure2D = gobjects(0);
        pop.Figure3D = gobjects(0);
        populationResults.(matlab.lang.makeValidName(folders(methodIndex))). ...
            (area) = pop;
        writetable(pop.BiasTable, fullfile(areaFolder, ...
            'PopulationBiasTable.csv'));
        writetable(pop.SummaryTable, fullfile(areaFolder, ...
            'PopulationConditionSummary.csv'));
        writetable(pop.AIxODSummaryTable, fullfile(areaFolder, ...
            'PopulationAIxODSummary.csv'));
        populationSummaryParts{writeIndex} = addAnalysisColumn( ...
            pop.SummaryTable, methods(methodIndex));
        aixodSummaryParts{writeIndex} = addAnalysisColumn( ...
            pop.AIxODSummaryTable, methods(methodIndex));
        runSummaryParts{writeIndex} = buildRunSummary( ...
            normalizedTables{methodIndex}, pop, methods(methodIndex), area);
    end
end

populationSummary = vertcat(populationSummaryParts{:});
aixodSummary = vertcat(aixodSummaryParts{:});
runSummary = vertcat(runSummaryParts{:});
sessionAudit = vertcat( ...
    buildSessionAudit(originalNormalized), ...
    buildSessionAudit(stimNormalized), ...
    buildSessionAudit(quickAllNormalized), ...
    buildSessionAudit(quick200Normalized));

writetable(populationSummary, fullfile(summaryFolder, ...
    'UnifiedPopulationConditionSummary.csv'));
writetable(aixodSummary, fullfile(summaryFolder, ...
    'UnifiedAIxODSummary.csv'));
writetable(runSummary, fullfile(summaryFolder, ...
    'UnifiedRunSummary.csv'));
writetable(sessionAudit, fullfile(sessionFolder, ...
    'UnifiedSessionAudit.csv'));

sourceHashAfter = fileSHA256(options.StateFile);
if sourceHashAfter ~= sourceHashBefore
    error('UnifiedBestChannel:InputChangedDuringRun', ...
        'The authoritative unit table changed during the unified run.');
end
inputProvenance = table(options.StateFile, sourceHashBefore, ...
    double(fileInfo.bytes), datetime(fileInfo.datenum, ...
    'ConvertFrom', 'datenum'), height(sourceTable), width(sourceTable) - 1, ...
    datetime('now', 'TimeZone', 'UTC'), true, ...
    'VariableNames', {'InputFile', 'SHA256', 'Bytes', 'LastModified', ...
    'Rows', 'Columns', 'RunCompletedAtUTC', 'HashUnchangedDuringRun'});
writetable(inputProvenance, fullfile(summaryFolder, ...
    'InputProvenance.csv'));

results = struct();
results.InputProvenance = inputProvenance;
results.Criteria = criteriaTable;
results.RunSummary = runSummary;
results.AIxODSummary = aixodSummary;
results.PopulationConditionSummary = populationSummary;
results.SessionAudit = sessionAudit;
results.Population = populationResults;
results.OriginalQuickDetails = originalDetails;
results.QuickAllDetails = quickAllDetails;
results.QuickWithin200umDetails = quick200Details;
results.OutputRoot = options.OutputRoot;
unified_results = results; %#ok<NASGU>
save(fullfile(options.OutputRoot, ...
    'UnifiedBestChannelReanalysisResults.mat'), ...
    'unified_results', '-v7.3');

writeOutputReadme(options.OutputRoot, options.StateFile, sourceHashBefore);
fprintf('\nUnified reanalysis complete. Outputs: %s\n', options.OutputRoot);
end


function [normalized, details] = prepareOriginalQuickAnalysis( ...
    sourceTable, outputRoot, options)
% Re-run the original fixed stimulation-channel Quick method through the
% same selected-channel AI/OD and p/Z preparation path as the two best-
% channel analyses. This prevents the comparison from inheriting a stale
% mixture of table fields or different downstream criteria.
detailFolder = fullfile(outputRoot, '00_OriginalQuick_StimChannel');
makeFolder(detailFolder);
rowCount = height(sourceTable);
UnitTableRow = (1:rowCount)';
BestChannel = double(sourceTable.StimElec);
Status = repmat("Success", rowCount, 1);
FixedChannelScore = zeros(rowCount, 1);
fixedSummary = table(UnitTableRow, BestChannel, Status, FixedChannelScore);
[prepared, aiODAudit] = PrepareBestQuickChannelPopulationTable( ...
    sourceTable, fixedSummary, "OriginalFixedStimElec", ...
    "FixedChannelScore", "Max");
[prepared, criteriaAudit] = PrepareBestQuickChannelSelectionCriteria( ...
    prepared, JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder, ...
    DominantEyeMethod="SelectedOD");

valid = aiODAudit.Status == "Success" & criteriaAudit.Status == "Success";
normalized = normalizePreparedTable(prepared, ...
    "Original Quick - stimulation channel", prepared.best_quick_AI, ...
    prepared.best_quick_OD_signed_for_eye, valid, BestChannel, ...
    nan(rowCount, 1), zeros(rowCount, 1), zeros(rowCount, 1), ...
    string(aiODAudit.Status), string(criteriaAudit.Status), ...
    criteriaAudit.BestMonoLP, criteriaAudit.BestMonoRP, ...
    false(rowCount, 1));
normalized.analysis_selection_metric(:) = "Fixed StimElec";
writetable(aiODAudit, fullfile(detailFolder, ...
    'OriginalStimChannel_AI_OD_Audit.csv'));
writetable(criteriaAudit, fullfile(detailFolder, ...
    'OriginalStimChannel_CriteriaAudit.csv'));
save(fullfile(detailFolder, 'PreparedPopulationInput.mat'), ...
    'normalized', '-v7.3');
details = struct('FixedChannelSummary', fixedSummary, ...
    'AIODAudit', aiODAudit, 'CriteriaAudit', criteriaAudit);
end


function [normalized, details] = prepareQuickAnalysis(sourceTable, ...
    stateFile, outputRoot, analysisName, folderName, maxPosition, options)
detailFolder = fullfile(outputRoot, folderName);
selectionFolder = fullfile(detailFolder, 'channel_selection');
makeFolder(detailFolder); makeFolder(selectionFolder);
[selectionSummary, channelScores, selectionMetadata, figures] = ...
    CorrelateQuickStimNoStimTunings(stateFile, ...
    OutputFolder=selectionFolder, SaveOutputs=true, MakePlot=false, ...
    FigureVisible=options.FigureVisible, ...
    MaxAbsRelativePosition=maxPosition);
closeFigureStruct(figures);
[prepared, aiODAudit] = PrepareBestQuickChannelPopulationTable( ...
    sourceTable, selectionSummary, "Correlation", "BestPearsonR", "Max");
[prepared, criteriaAudit] = PrepareBestQuickChannelSelectionCriteria( ...
    prepared, JimCacheFolder=options.JimCacheFolder, ...
    ClayCacheFolder=options.ClayCacheFolder, ...
    DominantEyeMethod="SelectedOD");

valid = aiODAudit.Status == "Success" & criteriaAudit.Status == "Success";
rowCount = height(prepared);
selectedChannel = nan(rowCount, 1);
selectionR = nan(rowCount, 1);
relativePosition = nan(rowCount, 1);
distanceMicrometers = nan(rowCount, 1);
selectionStatus = repmat("Missing", rowCount, 1);
changedByDistance = false(rowCount, 1);
for index = 1:height(selectionSummary)
    row = selectionSummary.UnitTableRow(index);
    if ~isfinite(row) || row < 1 || row > rowCount, continue, end
    selectedChannel(row) = selectionSummary.BestChannel(index);
    selectionR(row) = selectionSummary.BestPearsonR(index);
    relativePosition(row) = ...
        selectionSummary.BestRelativePositionToStim(index);
    distanceMicrometers(row) = ...
        selectionSummary.BestDistanceToStimMicrometers(index);
    selectionStatus(row) = string(selectionSummary.Status(index)) + ...
        "/" + string(aiODAudit.Status(row));
    if ismember('SelectionChangedByDistanceThreshold', ...
            selectionSummary.Properties.VariableNames)
        changedByDistance(row) = ...
            selectionSummary.SelectionChangedByDistanceThreshold(index);
    end
end

normalized = normalizePreparedTable(prepared, analysisName, ...
    prepared.best_quick_AI, prepared.best_quick_OD_signed_for_eye, ...
    valid, selectedChannel, selectionR, relativePosition, ...
    distanceMicrometers, selectionStatus, string(criteriaAudit.Status), ...
    criteriaAudit.BestMonoLP, criteriaAudit.BestMonoRP, changedByDistance);
writetable(aiODAudit, fullfile(detailFolder, ...
    'SelectedChannel_AI_OD_Audit.csv'));
writetable(criteriaAudit, fullfile(detailFolder, ...
    'SelectedChannel_CriteriaAudit.csv'));
save(fullfile(detailFolder, 'PreparedPopulationInput.mat'), ...
    'normalized', '-v7.3');
details = struct('SelectionSummary', selectionSummary, ...
    'SelectionMetadata', selectionMetadata, 'AIODAudit', aiODAudit, ...
    'CriteriaAudit', criteriaAudit, ...
    'MaxAbsRelativePosition', maxPosition);
% The full channel-level scores are already in channel_selection as CSV/MAT.
details.ChannelScoreRowCount = height(channelScores);
end


function normalized = normalizePreparedTable(prepared, analysisName, ...
    analysisAI, signedOD, sourceValid, selectedChannel, selectionR, ...
    relativePosition, distanceMicrometers, selectionStatus, ...
    criteriaStatus, monoLP, monoRP, changedByDistance)
required = {'SourceTableRow', 'Date', 'ROI', 'Hole', 'Monkey', ...
    'p_AI', 'Z3D_v_Z2D', 'Behav_bias_N', 'Behav_bias_S', ...
    'Behav_goodfit_N', 'Behav_goodfit_S'};
normalized = prepared(:, required);
rowCount = height(normalized);
normalized.Analysis = repmat(analysisName, rowCount, 1);
normalized.analysis_AI = analysisAI;
normalized.analysis_OD_signed = double(signedOD(:));
normalized.analysis_source_valid = logical(sourceValid(:));
normalized.analysis_selected_channel = double(selectedChannel(:));
normalized.analysis_selection_metric = repmat("Pearson r", rowCount, 1);
if startsWith(analysisName, "Stim-task")
    normalized.analysis_selection_metric(:) = "Not applicable";
end
normalized.analysis_selection_r = double(selectionR(:));
normalized.analysis_relative_position = double(relativePosition(:));
normalized.analysis_distance_micrometers = double(distanceMicrometers(:));
normalized.analysis_selection_status = string(selectionStatus(:));
normalized.analysis_criteria_status = string(criteriaStatus(:));
normalized.analysis_monoL_p = double(monoLP(:));
normalized.analysis_monoR_p = double(monoRP(:));
normalized.analysis_z3d_minus_z2d = ...
    extractNumericScalars(normalized.Z3D_v_Z2D);
normalized.analysis_neural_gate_pass = ...
    normalized.analysis_source_valid & ...
    normalized.analysis_monoL_p < 0.05 & ...
    normalized.analysis_monoR_p < 0.05 & ...
    isfinite(normalized.analysis_z3d_minus_z2d) & ...
    normalized.analysis_z3d_minus_z2d ~= 0;
normalized.analysis_unit_type = repmat("Unknown", rowCount, 1);
normalized.analysis_unit_type( ...
    normalized.analysis_z3d_minus_z2d < 0) = "2D";
normalized.analysis_unit_type( ...
    normalized.analysis_z3d_minus_z2d > 0) = "3D";
normalized.analysis_selection_changed_by_200um = logical(changedByDistance(:));
end


function summary = buildRunSummary(normalized, population, analysis, area)
areaRows = string(normalized.ROI) == area;
validRows = areaRows & normalized.analysis_source_valid;
gateRows = validRows & normalized.analysis_neural_gate_pass;
unitType = string(population.AIxODSummaryTable.UnitType);
row2D = find(unitType == "2D", 1);
row3D = find(unitType == "3D", 1);
Analysis = analysis;
Area = area;
SourceTableRows = nnz(areaRows);
SourceValidRows = nnz(validRows);
NeuralGatePassRows = nnz(gateRows);
Neural2DRows = nnz(gateRows & normalized.analysis_unit_type == "2D");
Neural3DRows = nnz(gateRows & normalized.analysis_unit_type == "3D");
Model2DUnits = valueAt(population.AIxODSummaryTable.NUnits, row2D, 0);
Model3DUnits = valueAt(population.AIxODSummaryTable.NUnits, row3D, 0);
P_AI_2D = valueAt(population.AIxODSummaryTable.P_AI, row2D, NaN);
P_AIxOD_2D = valueAt(population.AIxODSummaryTable.P_AIxOD, row2D, NaN);
R2_2D = valueAt(population.AIxODSummaryTable.R2, row2D, NaN);
P_AI_3D = valueAt(population.AIxODSummaryTable.P_AI, row3D, NaN);
P_AIxOD_3D = valueAt(population.AIxODSummaryTable.P_AIxOD, row3D, NaN);
R2_3D = valueAt(population.AIxODSummaryTable.R2, row3D, NaN);
MedianSelectionR = median(normalized.analysis_selection_r(validRows), 'omitnan');
MedianAbsDistanceMicrometers = median(abs( ...
    normalized.analysis_distance_micrometers(validRows)), 'omitnan');
SelectionChangedBy200umRows = nnz(validRows & ...
    normalized.analysis_selection_changed_by_200um);
summary = table(Analysis, Area, SourceTableRows, SourceValidRows, ...
    NeuralGatePassRows, Neural2DRows, Neural3DRows, ...
    Model2DUnits, Model3DUnits, P_AI_2D, P_AIxOD_2D, R2_2D, ...
    P_AI_3D, P_AIxOD_3D, R2_3D, MedianSelectionR, ...
    MedianAbsDistanceMicrometers, SelectionChangedBy200umRows);
end


function audit = buildSessionAudit(normalized)
audit = normalized(:, {'Analysis', 'SourceTableRow', 'Monkey', 'Date', ...
    'ROI', 'analysis_selected_channel', 'analysis_selection_metric', ...
    'analysis_selection_r', 'analysis_relative_position', ...
    'analysis_distance_micrometers', 'analysis_selection_status', ...
    'analysis_criteria_status', 'analysis_source_valid', ...
    'analysis_monoL_p', 'analysis_monoR_p', ...
    'analysis_z3d_minus_z2d', 'analysis_neural_gate_pass', ...
    'analysis_unit_type', 'analysis_selection_changed_by_200um'});
audit.Properties.VariableNames = {'Analysis', 'SourceTableRow', 'Monkey', ...
    'Date', 'Area', 'SelectedChannel', 'SelectionMetric', 'SelectionR', ...
    'RelativePosition', 'DistanceMicrometers', 'SelectionStatus', ...
    'CriteriaStatus', 'SourceValid', 'MonoLP', 'MonoRP', ...
    'Z3DMinusZ2D', 'NeuralGatePass', 'UnitType', ...
    'SelectionChangedBy200um'};
end


function output = addAnalysisColumn(input, analysis)
output = input;
output.Analysis = repmat(analysis, height(output), 1);
output = movevars(output, 'Analysis', 'Before', 1);
end


function files = savePopulationFigures(population, folder, folderName, area)
base = folderName + "_" + area;
files.TwoDPNG = fullfile(folder, base + "_Population_2D.png");
files.TwoDFIG = fullfile(folder, base + "_Population_2D.fig");
files.ThreeDPNG = fullfile(folder, base + "_Population_3D.png");
files.ThreeDFIG = fullfile(folder, base + "_Population_3D.fig");
exportgraphics(population.Figure2D, files.TwoDPNG, 'Resolution', 220);
savefig(population.Figure2D, files.TwoDFIG);
exportgraphics(population.Figure3D, files.ThreeDPNG, 'Resolution', 220);
savefig(population.Figure3D, files.ThreeDFIG);
end


function criteria = buildCriteriaTable(stateFile, hash, allChannelLimit)
Criterion = [ ...
    "Authoritative data table"; "Input integrity"; ...
    "Original Quick comparison source"; "Stim-task NoStim source"; ...
    "Best Quick channel source"; ...
    "Best Quick within 200 um source"; "Channel score"; ...
    "Correlation grid and normalization"; "AI"; "OD"; ...
    "Neural significance"; "2D/3D classification"; ...
    "Behavioral inclusion"; "Anatomical inclusion"; ...
    "Population interaction model"; "Eye merging"; ...
    "Outlier/influence exclusion"];
Value = [ ...
    stateFile; "SHA-256 " + hash + "; 251 source rows expected"; ...
    "3DMotionQuick tuning at fixed StimElec; selected-channel AI, Max OD, raw p_AI, and Z3D-Z2D recomputed through the shared Quick preparation path"; ...
    "3DMotionStim NoStim trials at StimElec"; ...
    "3DMotionQuick channel with maximum pooled Pearson r across all available channels (limit " + allChannelLimit + " contacts)"; ...
    "3DMotionQuick channel with maximum pooled Pearson r within +/-4 contacts (+/-200 um)"; ...
    "Pearson r only; no SSE selection"; ...
    "First/last four matched coherence bins; one whole-channel sample Z score across the 4 x 8 matrix"; ...
    "Recomputed/read from the selected neural source and selected channel"; ...
    "Max-response signed OD at selected source/channel; sign assigns eye; abs(OD) enters models, weights, and opacity"; ...
    "Raw selected-source MonoL p_AI < 0.05 AND MonoR p_AI < 0.05"; ...
    "Selected-source Z3D-Z2D: <0 is 2D, >0 is 3D"; ...
    "Both NoStim and Stim sigmoid fits good and finite for each cue"; ...
    "All AP values; no experiment-specific AP cutoff"; ...
    "MergedEyeBias ~ AI + AI:OD"; ...
    "Dominant and sign-flipped NonDominant perspective cues"; ...
    "None; no post hoc session deletion or influence-based exclusion"];
AppliesTo = ["All four"; "All four"; "Original Quick comparison"; ...
    "Stim-task NoStim"; ...
    "Best Quick - all channels"; "Best Quick - within 200 um"; ...
    "Two best-channel analyses"; "Two best-channel analyses"; ...
    "All four"; "All four"; "All four"; "All four"; "All four"; ...
    "All four"; "All four"; "All four"; "All four"];
criteria = table(Criterion, Value, AppliesTo);
end


function writeOutputReadme(outputRoot, inputFile, hash)
lines = [ ...
    "# Unified best-channel reanalysis (Max OD)"; ""; ...
    "All three main analyses and the original Quick comparison use the same authoritative table:"; ...
    "`" + inputFile + "`"; ...
    "SHA-256: `" + hash + "`"; ""; ...
    "Top-level accessible outputs:"; ...
    "- `summaries/UnifiedRunSummary.csv`: one row per analysis and area."; ...
    "- `summaries/UnifiedAIxODSummary.csv`: model results by 2D/3D type."; ...
    "- `summaries/UnifiedPopulationConditionSummary.csv`: cue-level results."; ...
    "- `summaries/UnifiedCriteria.csv`: complete shared specification."; ...
    "- `session_level/UnifiedSessionAudit.csv`: row-level selections and neural gates."; ...
    "- `00_...`, `01_...`, `02_...`, `03_...`: method-specific audits, tables, and figures."; ...
    "- `UnifiedBestChannelReanalysisResults.mat`: compact MATLAB result bundle."; ""; ...
    "No workbook refresh, AP cutoff, LSQ OD, SSE selection, or post hoc influence exclusion is applied."];
writelines(lines, fullfile(outputRoot, 'README.md'));
end


function values = extractNumericScalars(column)
values = nan(numel(column), 1);
if iscell(column)
    for row = 1:numel(column)
        value = column{row};
        if isnumeric(value) && isscalar(value), values(row) = value; end
    end
else
    values = double(column(:));
end
end


function value = valueAt(values, row, fallback)
if isempty(row), value = fallback; else, value = values(row); end
end


function hash = fileSHA256(filePath)
sha = System.Security.Cryptography.SHA256.Create();
stream = System.IO.File.OpenRead(char(filePath));
cleanup = onCleanup(@() stream.Close());
bytes = sha.ComputeHash(stream);
hash = string(char(System.BitConverter.ToString(bytes)));
hash = erase(hash, '-');
clear cleanup
end


function makeFolder(folder)
if ~isfolder(folder), mkdir(folder); end
end


function closeFigureStruct(figures)
if ~isstruct(figures), return, end
names = fieldnames(figures);
for index = 1:numel(names)
    handles = figures.(names{index});
    for handleIndex = 1:numel(handles)
        closeValidFigure(handles(handleIndex));
    end
end
end


function closeValidFigure(handle)
if ~isempty(handle) && all(isgraphics(handle, 'figure')), close(handle); end
end
