AddGoodTrialSDFToNeuroRespByNeuronTable( ...
    'C:/LoData/MotionData_ByStim_NeuroResp_ByNeuron.mat', ...
    'C:/LoData/TempData.mat', ...
    'C:/LoData/MotionData_ByStim_NeuroResp_ByNeuron_WithGoodTrialSDF.mat');
