function figureHandle = currentSpreadSaveAllCueRelativeChannelAIOD( ...
    result, outputDir)
%CURRENTSPREADSAVEALLCUERELATIVECHANNELAIOD Save the requested 1-by-5 plot.

arguments
    result (1, 1) struct
    outputDir (1, :) char
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

positions = result.relativePositions;
if ~isequal(positions, 0:4)
    warning('CurrentSpread:UnexpectedRelativePositions', ...
        'The requested figure is designed for relative positions 0:4.');
end

figureHandle = figure('Color', 'w', 'Visible', 'off', ...
    'Name', 'all_cues_ai_od_relative_channels_0_to_4', ...
    'Position', [30 50 2400 720]);
layout = tiledlayout(figureHandle, 1, numel(positions), ...
    'TileSpacing', 'compact', 'Padding', 'compact');
xGrid = linspace(-1, 1, 200)';
legendHandles = gobjects(numel(result.conditionNames), 1);

for positionIndex = 1:numel(positions)
    relativePosition = positions(positionIndex);
    axesHandle = nexttile(layout);
    hold(axesHandle, 'on')
    xline(axesHandle, 0, 'k--', 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
    yline(axesHandle, 0, 'k--', 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');

    counts = zeros(1, numel(result.conditionNames));
    populationR2 = NaN(1, numel(result.conditionNames));
    perspectiveRow = result.perspectiveModelSummary( ...
        result.perspectiveModelSummary.RelativeChannelPosition == ...
        relativePosition, :);
    for conditionIndex = 1:numel(result.conditionNames)
        rows = result.fitPoints.RelativeChannelPosition == relativePosition & ...
            result.fitPoints.ConditionIndex == conditionIndex;
        points = result.fitPoints(rows, :);
        counts(conditionIndex) = height(points);
        summaryRow = result.modelSummary( ...
            result.modelSummary.RelativeChannelPosition == relativePosition & ...
            result.modelSummary.ConditionIndex == conditionIndex, :);
        color = result.conditionColors(conditionIndex, :);
        if ~isempty(summaryRow)
            populationR2(conditionIndex) = summaryRow.PopulationR2;
        end

        if ~isempty(summaryRow) && isfinite(summaryRow.WeightedSlope) && ...
                isfinite(summaryRow.WeightedIntercept)
            lineHandle = plot(axesHandle, xGrid, ...
                summaryRow.WeightedIntercept + summaryRow.WeightedSlope .* xGrid, ...
                '-', 'Color', color, 'LineWidth', 2.3);
        else
            lineHandle = plot(axesHandle, NaN, NaN, '-', ...
                'Color', color, 'LineWidth', 2.3);
        end
        if positionIndex == 1
            legendHandles(conditionIndex) = lineHandle;
        end

        if ~isempty(points)
            scatterHandle = scatter(axesHandle, points.AI, ...
                points.DisplayedDeltaBias, ...
                42, color, 'o', 'filled', 'MarkerEdgeColor', color, ...
                'LineWidth', 1.0, 'HandleVisibility', 'off');
            scatterHandle.AlphaData = min(max(points.OD, 0), 1);
            scatterHandle.MarkerFaceAlpha = 'flat';
        end
    end

    axis(axesHandle, 'square')
    xlim(axesHandle, [-1 1])
    ylim(axesHandle, [-2.2 2.2])
    xticks(axesHandle, -1:0.5:1)
    xticklabels(axesHandle, {'-1', 'Away', '0', 'Towards', '1'})
    yticks(axesHandle, -2:1:2)
    if positionIndex == 1
        yticklabels(axesHandle, {'-2', 'Away', '0', 'Towards', '2'})
        ylabel(axesHandle, 'DeltaBias (non-dominant bias flipped)', ...
            'Interpreter', 'tex')
    else
        yticklabels(axesHandle, {})
    end
    xlabel(axesHandle, 'Local-channel asymmetry index')
    title(axesHandle, positionTitle(relativePosition), 'Interpreter', 'none')
    subtitleHandle = subtitle(axesHandle, { ...
        sprintf('N D/C/S/N = %d/%d/%d/%d', counts), ...
        sprintf('R^2 [AI + AI x OD] = %.2f/%.2f/%.2f/%.2f', ...
        populationR2), ...
        sprintf(['Merged perspective: R^2 = %.2f; ' ...
        'p(AI x OD) = %.3g'], perspectiveRow.R2, ...
        perspectiveRow.AIxODP)}, 'Interpreter', 'tex');
    subtitleHandle.FontSize = 9;
    box(axesHandle, 'on')
    set(axesHandle, 'FontSize', 10, 'LineWidth', 1, 'Layer', 'top')
end

title(layout, { ...
    'Jim MT 2D: all cues at relative channels 0 through +4', ...
    ['Local AI and local |OD|; NonDominant bias is flipped; ' ...
    'p = merged perspective AI x OD']}, ...
    'FontSize', 15, 'FontWeight', 'bold', 'Interpreter', 'none')
legendLabels = cellstr(result.conditionNames);
legendLabels{4} = 'NonDominant (bias flipped)';
legendHandle = legend(legendHandles, legendLabels, ...
    'Orientation', 'horizontal', 'Box', 'off');
legendHandle.Layout.Tile = 'south';

baseName = 'all_cues_ai_od_relative_channels_0_to_4';
savefig(figureHandle, fullfile(outputDir, [baseName '.fig']));
exportgraphics(figureHandle, fullfile(outputDir, [baseName '.png']), ...
    'Resolution', 300);
exportgraphics(figureHandle, fullfile(outputDir, [baseName '.pdf']), ...
    'ContentType', 'vector');

writetable(result.observationAudit, ...
    fullfile(outputDir, 'all_cue_channel_observation_audit.csv'));
writetable(result.fitPoints, ...
    fullfile(outputDir, 'all_cue_fit_points.csv'));
writetable(result.channelSummary, ...
    fullfile(outputDir, 'local_dominance_sign_change_summary.csv'));
writetable(result.modelSummary, ...
    fullfile(outputDir, 'all_cue_model_summary.csv'));
writetable(result.perspectiveModelSummary, ...
    fullfile(outputDir, 'merged_perspective_AI_plus_AIxOD_summary.csv'));

populationColumns = {'RelativeChannelPosition', 'ConditionIndex', ...
    'ConditionName', 'NPoints', 'NUnits', 'MeanAI', 'MeanDeltaBias', ...
    'MeanDisplayedDeltaBias', ...
    'MeanOD', 'WeightedIntercept', 'WeightedSlope', 'PopulationIntercept', ...
    'PopulationAI', 'PopulationAISE', 'PopulationAIP', ...
    'PopulationAIxOD', 'PopulationAIxODSE', 'PopulationAIxODP', ...
    'PopulationR2', 'PopulationAdjustedR2', 'PopulationRMSE'};
writetable(result.modelSummary(:, populationColumns), ...
    fullfile(outputDir, 'population_formula_AI_plus_AIxOD_summary.csv'));

fullInteractionColumns = {'RelativeChannelPosition', 'ConditionIndex', ...
    'ConditionName', 'NPoints', 'NUnits', 'MeanAI', 'MeanDeltaBias', ...
    'MeanDisplayedDeltaBias', ...
    'MeanOD', 'FullIntercept', 'FullAI', 'FullAISE', 'FullAIP', ...
    'FullOD', 'FullODSE', 'FullODP', 'FullAIxOD', 'FullAIxODSE', ...
    'FullAIxODP', 'FullR2', 'FullAdjustedR2', 'FullRMSE'};
writetable(result.modelSummary(:, fullInteractionColumns), ...
    fullfile(outputDir, 'literal_formula_AI_times_OD_summary.csv'));

save(fullfile(outputDir, 'all_cue_relative_channel_ai_od.mat'), 'result');
end


function label = positionTitle(relativePosition)
if relativePosition == 0
    label = 'Relative 0 (stimulation)';
else
    label = sprintf('Relative +%d', relativePosition);
end
end
