function [CombinedPatternTuningTable, CombinedPatternTuningBySpeedTable, ...
        CombinedPatternTuningSummary, ZeroTestResults, ...
        CombinedBinocularOpticFlowTable, ...
        CombinedBinocularOpticFlowSummary, BODIZeroTestResults] = ...
    RunCombinedLoEMFSTPatternTuningAnalysis128(outputDirectory, inputPaths)
%RUNCOMBINEDLOEMFSTPATTERNTUNINGANALYSIS128 Run the matched 1.28 analysis.
%   Lo uses its complete Z_quad == 2 classification. EM retains its FST/3D
%   tuning requirements and additionally requires Z3D_v_Z2D > 1.28.

arguments
    outputDirectory (1, 1) string = ""
    inputPaths.LoNeuroResp (1, 1) string = "C:\LoData\NeuroRespUnitTable.mat"
    inputPaths.LoLateral2D (1, 1) string = "C:\LoData\LateralMotionRawFRTable.mat"
    inputPaths.LoMID (1, 1) string = "C:\LoData\MIDTable.mat"
    inputPaths.EMUnitTableGof (1, 1) string = "C:\EM\PopulationAnalysis\unit_table_gof.mat"
end

[CombinedPatternTuningTable, CombinedPatternTuningBySpeedTable, ...
    CombinedPatternTuningSummary, ZeroTestResults, ...
    CombinedBinocularOpticFlowTable, ...
    CombinedBinocularOpticFlowSummary, BODIZeroTestResults] = ...
    RunCombinedLoEMFSTPatternTuningAnalysis( ...
    outputDirectory, ...
    LoNeuroResp=inputPaths.LoNeuroResp, ...
    LoLateral2D=inputPaths.LoLateral2D, ...
    LoMID=inputPaths.LoMID, ...
    EMUnitTableGof=inputPaths.EMUnitTableGof, ...
    SelectionMode="both-1.28");
end
