function [StatisticsTable, VerificationTable, LoResultTable, ...
        EMResultTable, CombinedResultTable] = ...
    RunFSTPDIAndBODIPaperComparison128(outputRoot, inputPaths, options)
%RUNFSTPDIANDBODIPAPERCOMPARISON128 Rebuild and compare strict FST3D sets.
%   This is the one-command paper runner. It rebuilds the established
%   PDI/BODI outputs, verifies them against the Aug 12, 2026 summary, then
%   exports a Lo-versus-EM statistics table and vector/raster figure.

arguments
    outputRoot (1, 1) string = "C:\EM\PatternTuning\Final_128"
    inputPaths.LoNeuroResp (1, 1) string = "C:\LoData\NeuroRespUnitTable.mat"
    inputPaths.LoLateral2D (1, 1) string = "C:\LoData\LateralMotionRawFRTable.mat"
    inputPaths.LoMID (1, 1) string = "C:\LoData\MIDTable.mat"
    inputPaths.EMUnitTableGof (1, 1) string = ...
        "C:\EM\PopulationAnalysis\unit_table_gof.mat"
    options.BootstrapIterations (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10000
    options.BootstrapSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 1280812
end

[LoResultTable, EMResultTable, CombinedResultTable] = ...
    RunFSTPDIAndBODIAnalysis128(outputRoot, ...
    LoNeuroResp=inputPaths.LoNeuroResp, ...
    LoLateral2D=inputPaths.LoLateral2D, ...
    LoMID=inputPaths.LoMID, ...
    EMUnitTableGof=inputPaths.EMUnitTableGof);

LoZeroTests = BuildFSTPDIAndBODIZeroTests(LoResultTable);
EMZeroTests = BuildFSTPDIAndBODIZeroTests(EMResultTable);
CombinedZeroTests = BuildFSTPDIAndBODIZeroTests(CombinedResultTable);
VerificationTable = VerifyFSTPDIAndBODIAug12Summary( ...
    LoResultTable, EMResultTable, CombinedResultTable, ...
    LoZeroTests, EMZeroTests, CombinedZeroTests);
StatisticsTable = BuildFSTDatasetComparisonStatistics( ...
    LoResultTable, EMResultTable, LoZeroTests, EMZeroTests, ...
    BootstrapIterations=options.BootstrapIterations, ...
    BootstrapSeed=options.BootstrapSeed);

comparisonDirectory = fullfile(outputRoot, 'PaperComparison');
if ~isfolder(comparisonDirectory)
    mkdir(comparisonDirectory);
end
prefix = "FST3D_Lo58_vs_EM24_PDI_BODI";
statisticsPath = fullfile(comparisonDirectory, prefix + "_Statistics.csv");
verificationPath = fullfile(comparisonDirectory, prefix + ...
    "_Aug12Verification.csv");
matPath = fullfile(comparisonDirectory, prefix + "_Analysis.mat");
figureBase = fullfile(comparisonDirectory, prefix + "_Figure");

writetable(StatisticsTable, statisticsPath);
writetable(VerificationTable, verificationPath);
AnalysisConfig = struct();
AnalysisConfig.Generated = datetime('now');
AnalysisConfig.InputPaths = inputPaths;
AnalysisConfig.LoSelection = 'ROI==FST & sig_Anova_CLR & Z_quad==2';
AnalysisConfig.EMSelection = 'ROI==FST & ND==3D & Z3D_v_Z2D>1.28';
AnalysisConfig.PDI = ...
    'TDI for Toward; ADI for Away; matched slow 2D speed (~4.2 deg/s)';
AnalysisConfig.BODI = ...
    ['(Combined_FR-Stereo_FR)/(Combined_FR+Stereo_FR), using coherence ' ...
    '+1 for Toward and -1 for Away'];
AnalysisConfig.EffectDirection = 'EM minus Lo';
AnalysisConfig.BetweenDatasetTest = ...
    'Two-sided Wilcoxon rank-sum; Bonferroni across PDI and BODI';
AnalysisConfig.HedgesG = ...
    'Bias-corrected pooled-SD standardized mean difference; approximate 95% CI';
AnalysisConfig.CliffsDelta = ...
    'P(EM>Lo)-P(EM<Lo); deterministic percentile-bootstrap 95% CI';
AnalysisConfig.BootstrapIterations = options.BootstrapIterations;
AnalysisConfig.BootstrapSeed = options.BootstrapSeed;
AnalysisConfig.Aug12Verification = ...
    'Counts exact; rounded means/medians within 0.0005; p values within 1% relative error';
save(matPath, 'StatisticsTable', 'VerificationTable', ...
    'LoResultTable', 'EMResultTable', 'CombinedResultTable', ...
    'LoZeroTests', 'EMZeroTests', 'CombinedZeroTests', 'AnalysisConfig', '-v7.3');
OutputPaths = MakeFSTPDIAndBODIPaperFigure( ...
    LoResultTable, EMResultTable, StatisticsTable, figureBase);

fprintf('\nPaper comparison complete: Lo n=%d; EM n=%d.\n', ...
    height(LoResultTable), height(EMResultTable));
disp(StatisticsTable(:, {'Metric', 'Lo_N_Valid', 'EM_N_Valid', ...
    'MeanDifference_EM_Minus_Lo', 'HedgesG_EM_Minus_Lo', ...
    'CliffsDelta_EM_Minus_Lo', 'PValue_Bonferroni'}));
fprintf('Aug 12 verification: %d/%d checks passed.\n', ...
    nnz(VerificationTable.Pass), height(VerificationTable));
fprintf('Statistics: %s\n', statisticsPath);
fprintf('Raster figure: %s\n', OutputPaths.PNG);
fprintf('Vector figures: %s and %s\n', OutputPaths.PDF, OutputPaths.SVG);
end
