function [unit_table_stim, SessionManifest, PipelineMetadata] = ...
    RunAllUnitTableStimTunings(options)
%RUNALLUNITTABLESTIMTUNINGS Build the population Stim-file tuning table.
%
% RunAllUnitTableStimTunings() reads the authoritative unit_table_gof and
% writes a new, resumable population result under
% C:\EM\StimTuningAnalysis. The source table and all P: recordings are read
% only.

arguments
    options.UnitTableGofFile (1, 1) string = ...
        "C:\EM\PopulationAnalysis\unit_table_gof.mat"
    options.OutputFolder (1, 1) string = "C:\EM\StimTuningAnalysis"
    options.Rows (1, :) double {mustBeInteger, mustBePositive} = []
    options.ApplyEyeCheck (1, 1) logical = true
    options.RequireEyeCheck (1, 1) logical = false
    options.Resume (1, 1) logical = true
    options.OverwriteOutput (1, 1) logical = false
    options.CheckpointEvery (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10
    options.DryRun (1, 1) logical = false
    options.FailFast (1, 1) logical = false
end

[unit_table_stim, SessionManifest, PipelineMetadata] = ...
    BuildUnitTableStimTunings( ...
    options.UnitTableGofFile, options.OutputFolder, ...
    Rows=options.Rows, ApplyEyeCheck=options.ApplyEyeCheck, ...
    RequireEyeCheck=options.RequireEyeCheck, ...
    Resume=options.Resume, OverwriteOutput=options.OverwriteOutput, ...
    CheckpointEvery=options.CheckpointEvery, ...
    RecursiveSearch=false, DryRun=options.DryRun, ...
    FailFast=options.FailFast);
end
