%% FST meta-2D: ordinary DeltaBias ~ AI + AI:OD R-squared

clear; close all
interactiveRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(interactiveRoot, fullfile(interactiveRoot, 'common'), ...
    fullfile(interactiveRoot, 'ordinary_ai_od'));
cacheFile = "C:\EM\CurrentSpread\02_gaussian\" + ...
    "InteractiveGaussianMetaPopulation\FST\" + ...
    "GaussianMetaPopulationSigmaCache.mat";
if ~isfile(cacheFile)
    BuildInteractiveGaussianMetaPopulationSuite(Area="FST");
end
fst2DAllCueOrdinaryR2 = ...
    ExploreInteractiveGaussianMetaPopulationAllCueOrdinaryR2( ...
    CacheFile=cacheFile, UnitType="2D");
