%% FST meta-3D: distance to OD-weighted Type-II population lines

clear; close all
interactiveRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(interactiveRoot, fullfile(interactiveRoot, 'common'), ...
    fullfile(interactiveRoot, 'type2_distance'));
cacheFile = "C:\EM\CurrentSpread\02_gaussian\" + ...
    "InteractiveGaussianMetaPopulation\FST\" + ...
    "GaussianMetaPopulationSigmaCache.mat";
if ~isfile(cacheFile)
    BuildInteractiveGaussianMetaPopulationSuite(Area="FST");
end
fst3DAllCueType2Distance = ...
    ExploreInteractiveGaussianMetaPopulationAllCueType2Distance( ...
    CacheFile=cacheFile, UnitType="3D");
