%% Launch MT 2D Type-II-distance Gaussian-meta explorer with correlation OD

clear; close all
scriptFolder = fileparts(mfilename('fullpath'));
interactiveFolder = fileparts(scriptFolder);
addpath(fullfile(interactiveFolder, 'common'), ...
    fullfile(interactiveFolder, 'type2_distance'));

cacheFile = ...
    "C:\EM\CurrentSpread\02_gaussian\" + ...
    "InteractiveGaussianMetaPopulation\CorrelationOD\MT\" + ...
    "GaussianMetaPopulationSigmaCache.mat";
if ~isfile(cacheFile)
    fprintf(['Correlation-OD interactive cache is missing; ' ...
        'building the 1000-sigma cache.\n']);
    BuildInteractiveGaussianMetaPopulationCache( ...
        Area="MT", ODDefinition="Correlation");
end

interactiveGaussianMetaPopulationAllCueType2DistanceCorrelationOD = ...
    ExploreInteractiveGaussianMetaPopulationAllCueType2Distance( ...
    CacheFile=cacheFile, UnitType="2D");
