%% Launch MT 2D ordinary-R2 Gaussian-meta explorer with correlation OD

clear; close all
scriptFolder = fileparts(mfilename('fullpath'));
interactiveFolder = fileparts(scriptFolder);
addpath(fullfile(interactiveFolder, 'common'), ...
    fullfile(interactiveFolder, 'ordinary_ai_od'));

cacheFile = ...
    "C:\EM\CurrentSpread\02_gaussian\" + ...
    "InteractiveGaussianMetaPopulation\CorrelationOD\MT\" + ...
    "GaussianMetaPopulationSigmaCache.mat";
if ~isfile(cacheFile)
    fprintf(['Correlation-OD interactive cache is missing; ' ...
        'building the 1000-sigma cache.\n']);
    BuildInteractiveGaussianMetaPopulationCache( ...
        Area="MT", ODDefinition="Correlation");
end

interactiveGaussianMetaPopulationAllCueOrdinaryR2CorrelationOD = ...
    ExploreInteractiveGaussianMetaPopulationAllCueOrdinaryR2( ...
    CacheFile=cacheFile, UnitType="2D");
