%% Launch MT 2D Gaussian-meta explorer with correlation-defined OD

clear; close all
scriptFolder = fileparts(mfilename('fullpath'));
interactiveFolder = fileparts(scriptFolder);
addpath(fullfile(interactiveFolder, 'common'), ...
    fullfile(interactiveFolder, 'cv_ai_od'));

cacheFile = ...
    "C:\EM\CurrentSpread\02_gaussian\" + ...
    "InteractiveGaussianMetaPopulation\CorrelationOD\MT\" + ...
    "GaussianMetaPopulationSigmaCache.mat";
if ~isfile(cacheFile)
    fprintf(['Correlation-OD interactive cache is missing; ' ...
        'building the 1000-sigma cache.\n']);
    BuildInteractiveGaussianMetaPopulationCache( ...
        Area="MT", ODDefinition="Correlation");
end

interactiveGaussianMetaPopulationAllCueR2CorrelationOD = ...
    ExploreInteractiveGaussianMetaPopulationAllCueR2( ...
    CacheFile=cacheFile, UnitType="2D");
