function app = ExploreGaussianMetaPopulationApp(options)
%EXPLOREGAUSSIANMETAPOPULATIONAPP Unified cached population selector.
%
% The app switches among MT/FST, stimulation-site 2D/3D class, and cached
% optimization methods. Channel-first behavioral prediction is the default;
% the older meta-tuning views remain available for comparison. Max-OD and
% correlation-OD use separate app instances and separate caches.

arguments
    options.ODDefinition (1, 1) string ...
        {mustBeMember(options.ODDefinition, ["Max", "Correlation"])} = "Max"
    options.InitialArea (1, 1) string ...
        {mustBeMember(options.InitialArea, ["MT", "FST"])} = "MT"
    options.InitialUnitType (1, 1) string ...
        {mustBeMember(options.InitialUnitType, ["2D", "3D"])} = "2D"
    options.InitialMethod (1, 1) string ...
        {mustBeMember(options.InitialMethod, ...
        ["ChannelPrediction", "CV", "Ordinary", "Distance"])} = ...
        "ChannelPrediction"
    options.CacheRoot (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation"]
    options.Position (1, 4) double = [60 60 1540 930]
    options.CorrelationFaceAlphaFloor (1, 1) double ...
        {mustBeGreaterThanOrEqual(options.CorrelationFaceAlphaFloor, 0), ...
        mustBeLessThanOrEqual(options.CorrelationFaceAlphaFloor, 1)} = 0
    options.CorrelationEdgeAlpha (1, 1) double ...
        {mustBeGreaterThanOrEqual(options.CorrelationEdgeAlpha, 0), ...
        mustBeLessThanOrEqual(options.CorrelationEdgeAlpha, 1)} = 0.95
    options.MarkerSize (1, 1) double ...
        {mustBeGreaterThanOrEqual(options.MarkerSize, 8), ...
        mustBeLessThanOrEqual(options.MarkerSize, 200)} = 42
    options.MarkerEdgeWidth (1, 1) double ...
        {mustBeGreaterThanOrEqual(options.MarkerEdgeWidth, 0.25), ...
        mustBeLessThanOrEqual(options.MarkerEdgeWidth, 5)} = 1.25
    options.MarkerFaceMode (1, 1) string ...
        {mustBeMember(options.MarkerFaceMode, ["Color", "Grayscale"])} = ...
        "Color"
end

commonFolder = string(fileparts(mfilename('fullpath')));
interactiveRoot = string(fileparts(commonFolder));
cvFolder = fullfile(interactiveRoot, 'cv_ai_od');
ordinaryFolder = fullfile(interactiveRoot, 'ordinary_ai_od');
distanceFolder = fullfile(interactiveRoot, 'type2_distance');
channelPredictionFolder = fullfile(interactiveRoot, 'channel_prediction');
addpath(interactiveRoot, commonFolder, cvFolder, ordinaryFolder, ...
    distanceFolder, channelPredictionFolder);

currentViewer = struct();
currentSelection = struct('Area', options.InitialArea, ...
    'UnitType', options.InitialUnitType, ...
    'Method', options.InitialMethod);
if options.ODDefinition == "Correlation"
    initialEdgeAlpha = options.CorrelationEdgeAlpha;
else
    initialEdgeAlpha = 0.85;
end
displaySettings = struct( ...
    'MarkerSize', options.MarkerSize, ...
    'MarkerEdgeAlpha', initialEdgeAlpha, ...
    'MarkerEdgeWidth', options.MarkerEdgeWidth, ...
    'MarkerFaceMode', options.MarkerFaceMode);
renderSelection(currentSelection);

app = struct();
app.ODDefinition = options.ODDefinition;
app.GetCurrentViewer = @getCurrentViewer;
app.GetDisplaySettings = @getDisplaySettings;
app.Show = @renderSelection;

    function viewer = getCurrentViewer()
        viewer = currentViewer;
    end

    function settings = getDisplaySettings()
        settings = displaySettings;
        if isfield(currentViewer, 'GetDisplaySettings') && ...
                isa(currentViewer.GetDisplaySettings, 'function_handle')
            settings = currentViewer.GetDisplaySettings();
        end
    end

    function renderSelection(selection)
        selection.Area = string(selection.Area);
        selection.UnitType = string(selection.UnitType);
        selection.Method = string(selection.Method);
        previousViewer = currentViewer;
        if isfield(previousViewer, 'Figure') && ...
                isvalid(previousViewer.Figure)
            if isfield(previousViewer, 'GetDisplaySettings') && ...
                    isa(previousViewer.GetDisplaySettings, 'function_handle')
                displaySettings = previousViewer.GetDisplaySettings();
            end
            previousViewer.Figure.Name = sprintf( ...
                'Loading %s %s %s...', selection.Area, ...
                selection.UnitType, methodLabel(selection.Method));
            drawnow
        end

        configuration = loadConfiguration(selection);
        if options.ODDefinition == "Correlation"
            faceAlphaFloor = options.CorrelationFaceAlphaFloor;
        else
            faceAlphaFloor = 0;
        end
        if selection.Method == "ChannelPrediction"
            newViewer = ExploreGaussianChannelBiasPrediction( ...
                ObjectiveFile=configuration.ObjectiveFile, ...
                InitialSigma=configuration.InitialSigma, ...
                MarkerFaceAlphaFloor=faceAlphaFloor, ...
                MarkerEdgeAlpha=displaySettings.MarkerEdgeAlpha, ...
                MarkerSize=displaySettings.MarkerSize, ...
                MarkerEdgeWidth=displaySettings.MarkerEdgeWidth, ...
                MarkerFaceMode=displaySettings.MarkerFaceMode, ...
                ReserveSelectionRow=true, Visible="off", ...
                Position=options.Position);
        else
            newViewer = ExploreInteractiveGaussianMetaPopulation( ...
                CacheFile=configuration.CacheFile, ...
                UnitType=selection.UnitType, ...
                MetricMode=configuration.MetricMode, ...
                MetricPerCue=configuration.MetricPerCue, ...
                ObjectiveValues=configuration.ObjectiveValues, ...
                ObjectiveLabel=configuration.ObjectiveLabel, ...
                InitialSigma=configuration.InitialSigma, ...
                MarkerFaceAlphaFloor=faceAlphaFloor, ...
                MarkerEdgeAlpha=displaySettings.MarkerEdgeAlpha, ...
                MarkerSize=displaySettings.MarkerSize, ...
                MarkerEdgeWidth=displaySettings.MarkerEdgeWidth, ...
                MarkerFaceMode=displaySettings.MarkerFaceMode, ...
                ReserveSelectionRow=true, Visible="off", ...
                Position=options.Position);
        end
        addSelectionControls(newViewer, selection);
        if selection.Method == "ChannelPrediction"
            newViewer.Figure.Name = sprintf( ...
                '%s-OD Gaussian channel-prediction app', ...
                options.ODDefinition);
        else
            newViewer.Figure.Name = sprintf( ...
                '%s-OD Gaussian-meta population app', ...
                options.ODDefinition);
        end
        newViewer.Figure.Visible = 'on';
        currentViewer = newViewer;
        currentSelection = selection;
        if isfield(previousViewer, 'Figure') && ...
                isvalid(previousViewer.Figure)
            close(previousViewer.Figure);
        end
    end

    function addSelectionControls(viewer, selection)
        areaDropDown = uidropdown(viewer.ControlGrid, ...
            'Items', {'Area: MT', 'Area: FST'}, ...
            'ItemsData', {'MT', 'FST'}, 'Value', char(selection.Area), ...
            'Tooltip', 'Select cortical area');
        areaDropDown.Layout.Row = 1;
        areaDropDown.Layout.Column = 1;
        unitDropDown = uidropdown(viewer.ControlGrid, ...
            'Items', {'Population: 2D', 'Population: 3D'}, ...
            'ItemsData', {'2D', '3D'}, 'Value', char(selection.UnitType), ...
            'Tooltip', 'Select stimulation-channel unit class');
        unitDropDown.Layout.Row = 1;
        unitDropDown.Layout.Column = 2;
        methodDropDown = uidropdown(viewer.ControlGrid, ...
            'Items', {'Method: channel-first ordinary R2 (Dom AI x |OD|)', ...
            'Method: meta CV AI + AI:OD', ...
            'Method: ordinary AI + AI:OD', ...
            'Method: Type-II distance'}, ...
            'ItemsData', {'ChannelPrediction', 'CV', 'Ordinary', 'Distance'}, ...
            'Value', char(selection.Method), ...
            'Tooltip', 'Select sigma optimization method');
        methodDropDown.Layout.Row = 1;
        methodDropDown.Layout.Column = [3 4];
        areaDropDown.ValueChangedFcn = @selectionChanged;
        unitDropDown.ValueChangedFcn = @selectionChanged;
        methodDropDown.ValueChangedFcn = @selectionChanged;

        function selectionChanged(~, ~)
            nextSelection = struct( ...
                'Area', string(areaDropDown.Value), ...
                'UnitType', string(unitDropDown.Value), ...
                'Method', string(methodDropDown.Value));
            renderSelection(nextSelection);
        end
    end

    function configuration = loadConfiguration(selection)
        areaRoot = options.CacheRoot;
        if options.ODDefinition == "Correlation"
            areaRoot = fullfile(areaRoot, 'CorrelationOD');
        end
        areaRoot = fullfile(areaRoot, selection.Area);
        cacheFile = fullfile(areaRoot, ...
            'GaussianMetaPopulationSigmaCache.mat');
        [objectiveFolder, objectiveFile] = objectivePath( ...
            areaRoot, selection.UnitType, selection.Method);
        if selection.Method == "ChannelPrediction"
            if needsChannelCacheBuild(cacheFile)
                BuildInteractiveGaussianMetaPopulationCache( ...
                    Area=selection.Area, ODDefinition=options.ODDefinition, ...
                    OutputFolder=areaRoot, ValidateAgainstBuilder=false);
            end
            if needsChannelObjectiveBuild(cacheFile, objectiveFile)
                BuildGaussianChannelBiasPredictionObjective( ...
                    CacheFile=cacheFile, UnitType=selection.UnitType, ...
                    OutputFolder=objectiveFolder);
            end
        elseif needsBuild(cacheFile, objectiveFile)
            BuildInteractiveGaussianMetaPopulationSuite( ...
                Area=selection.Area, ODDefinition=options.ODDefinition, ...
                OutputRoot=areaRoot, ValidateAgainstBuilder=false);
        end

        configuration = struct();
        configuration.CacheFile = cacheFile;
        configuration.ObjectiveFile = objectiveFile;
        switch selection.Method
            case "ChannelPrediction"
                loaded = load(objectiveFile, ...
                    'gaussian_channel_bias_prediction');
                objective = loaded.gaussian_channel_bias_prediction;
                configuration.MetricMode = "";
                configuration.MetricPerCue = [];
                configuration.ObjectiveValues = objective.SumFourCueOrdinaryR2;
                configuration.ObjectiveLabel = ...
                    "Sum of ordinary cue R2 from dominant AI x |OD|";
            case "CV"
                loaded = load(objectiveFile, 'all_cue_r2_optimization');
                objective = loaded.all_cue_r2_optimization;
                configuration.MetricMode = "SumFourCueR2";
                configuration.MetricPerCue = objective.CrossValidatedR2;
                configuration.ObjectiveValues = ...
                    objective.SumFourCueCrossValidatedR2;
                configuration.ObjectiveLabel = ...
                    "Sum of four cue CV R^2: AI + AI:OD";
            case "Ordinary"
                loaded = load(objectiveFile, ...
                    'all_cue_ordinary_r2_optimization');
                objective = loaded.all_cue_ordinary_r2_optimization;
                configuration.MetricMode = "SumFourCueOrdinaryR2";
                configuration.MetricPerCue = objective.PerCueR2;
                configuration.ObjectiveValues = objective.SumFourCueR2;
                configuration.ObjectiveLabel = ...
                    "Sum of four ordinary R^2: AI + AI:OD";
            case "Distance"
                loaded = load(objectiveFile, ...
                    'all_cue_type2_distance_optimization');
                objective = loaded.all_cue_type2_distance_optimization;
                configuration.MetricMode = ...
                    "SumFourCueMeanSquaredDistance";
                configuration.MetricPerCue = ...
                    objective.PerCueMeanSquaredDistance;
                configuration.ObjectiveValues = ...
                    objective.SumFourCueMeanSquaredDistance;
                configuration.ObjectiveLabel = ...
                    "Sum of four cue mean squared distances";
        end
        configuration.InitialSigma = objective.BestSigma;
        configuration.ObjectiveFolder = objectiveFolder;
    end
end


function [folder, fileName] = objectivePath(areaRoot, unitType, method)
switch method
    case "ChannelPrediction"
        folder = fullfile(areaRoot, unitType, ...
            'ChannelFirstBiasPrediction_DominantAIxOD_OrdinaryR2_SourceStimBothEyes');
        fileName = fullfile(folder, ...
            'GaussianChannelBiasPredictionOptimization.mat');
    case "CV"
        folder = fullfile(areaRoot, unitType, 'AllCueR2Optimization');
        fileName = fullfile(folder, ...
            'AllCueR2GaussianMetaOptimization.mat');
    case "Ordinary"
        folder = fullfile(areaRoot, unitType, ...
            'AllCueOrdinaryR2Optimization');
        fileName = fullfile(folder, ...
            'AllCueOrdinaryR2GaussianMetaOptimization.mat');
    case "Distance"
        folder = fullfile(areaRoot, unitType, ...
            'AllCueType2DistanceOptimization');
        fileName = fullfile(folder, ...
            'AllCueType2DistanceGaussianMetaOptimization.mat');
end
end


function value = needsChannelCacheBuild(cacheFile)
value = true;
if ~isfile(cacheFile)
    return
end
try
    loaded = load(cacheFile, 'cache');
    required = {'ChannelAI', 'ChannelSignedOD', ...
        'ChannelEligibleForPrediction', 'ChannelRelativePositions', ...
        'StimReferenceOD', 'BehaviorByPhysicalCue', ...
        'BehaviorValidByPhysicalCue', 'StimZ3DMinusZ2D'};
    value = ~isfield(loaded, 'cache') || ...
        ~all(isfield(loaded.cache, required));
catch
    value = true;
end
end


function value = needsChannelObjectiveBuild(cacheFile, objectiveFile)
value = true;
if ~isfile(objectiveFile)
    return
end
try
    loaded = load(objectiveFile, 'gaussian_channel_bias_prediction');
    result = loaded.gaussian_channel_bias_prediction;
    if ~isfield(result, 'SchemaVersion') || result.SchemaVersion < 5 || ...
            ~isfield(result, 'CohortDefinition') || ...
            result.CohortDefinition ~= "SourceStimBothEyes_ChannelBothEyes_v1" || ...
            ~isfield(result, 'FitMethod') || result.FitMethod ~= "OrdinaryR2" || ...
            ~isfield(result, 'PredictorMode') || result.PredictorMode ~= "DominantAIxOD"
        return
    end
    cacheInfo = dir(cacheFile);
    objectiveInfo = dir(objectiveFile);
    value = objectiveInfo.datenum < cacheInfo.datenum;
catch
    value = true;
end
end


function value = needsBuild(cacheFile, objectiveFile)
value = ~isfile(cacheFile) || ~isfile(objectiveFile);
if value
    return
end
try
    loaded = load(cacheFile, 'cache');
    cache = loaded.cache;
    hasStimReference = isfield(cache, 'SchemaVersion') && ...
        double(cache.SchemaVersion) >= 5 && ...
        isfield(cache, 'StimChannelReferenceSigma') && ...
        abs(double(cache.StimChannelReferenceSigma) - 0.01) <= 1e-12 && ...
        isfield(cache, 'RefreshFromWorkbooks') && ...
        ~cache.RefreshFromWorkbooks && ...
        isfield(cache, 'Validation') && ...
        isfield(cache.Validation, 'StimChannelReference') && ...
        cache.Validation.StimChannelReference.Passed && ...
        isfield(cache, 'ChannelEligibleForPrediction') && ...
        isfield(cache, 'BehaviorByPhysicalCue');
    if ~hasStimReference
        value = true;
        return
    end
catch
    value = true;
    return
end
cacheInfo = dir(cacheFile);
objectiveInfo = dir(objectiveFile);
value = objectiveInfo.datenum < cacheInfo.datenum;
end


function label = methodLabel(method)
switch method
    case "ChannelPrediction"
        label = 'channel-first ordinary R2 (Dom AI x |OD|)';
    case "CV"
        label = 'CV AI + AI:OD';
    case "Ordinary"
        label = 'ordinary AI + AI:OD';
    otherwise
        label = 'Type-II distance';
end
end
