function app = ExploreInteractiveGaussianMetaPopulationAllCueType2Distance(options)
%EXPLOREINTERACTIVEGAUSSIANMETAPOPULATIONALLCUETYPE2DISTANCE Launch distance UI.
%
% This viewer uses the existing dense scatter cache. Its default sigma
% minimizes the sum of the four cue-wise mean squared perpendicular
% distances to the displayed OD-weighted Type II regression lines.

arguments
    options.CacheFile (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\" + ...
        "GaussianMetaPopulationSigmaCache.mat"]
    options.ObjectiveFolder (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\" + ...
        "AllCueType2DistanceOptimization"]
    options.Visible (1, 1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.Position (1, 4) double = [60 60 1540 900]
    options.SaveObjectiveResults (1, 1) logical = true
end

if options.SaveObjectiveResults
    objective = BuildAllCueType2DistanceGaussianMetaObjective( ...
        CacheFile=options.CacheFile, OutputFolder=options.ObjectiveFolder);
else
    objectiveFile = fullfile(options.ObjectiveFolder, ...
        'AllCueType2DistanceGaussianMetaOptimization.mat');
    if ~isfile(objectiveFile)
        error('AllCueType2DistanceGaussianMeta:MissingObjective', ...
            'Saved all-cue distance objective not found: %s', objectiveFile);
    end
    loaded = load(objectiveFile, ...
        'all_cue_type2_distance_optimization');
    objective = loaded.all_cue_type2_distance_optimization;
end

app = ExploreInteractiveGaussianMetaPopulation( ...
    CacheFile=options.CacheFile, ...
    MetricMode="SumFourCueMeanSquaredDistance", ...
    MetricPerCue=objective.PerCueMeanSquaredDistance, ...
    ObjectiveValues=objective.SumFourCueMeanSquaredDistance, ...
    ObjectiveLabel="Sum of four cue mean squared distances", ...
    InitialSigma=objective.BestSigma, ...
    Visible=options.Visible, Position=options.Position);
app.Objective = objective;
end
