function app = ExploreInteractiveGaussianMetaPopulationAllCueR2(options)
%EXPLOREINTERACTIVEGAUSSIANMETAPOPULATIONALLCUER2 Launch all-cue optimizer UI.
%
% This viewer uses the existing 1000-sigma scatter cache. Its default sigma
% maximizes the sum of the Dominant, Combined, Stereo, and NonDominant
% population R-squared values. The population plot itself is unchanged.

arguments
    options.CacheFile (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\" + ...
        "GaussianMetaPopulationSigmaCache.mat"]
    options.Visible (1, 1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.Position (1, 4) double = [60 60 1540 900]
    options.SaveObjectiveResults (1, 1) logical = true
end

if options.SaveObjectiveResults
    objective = BuildAllCueR2GaussianMetaObjective( ...
        CacheFile=options.CacheFile);
else
    objectiveFile = ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\AllCueR2Optimization\" + ...
        "AllCueR2GaussianMetaOptimization.mat";
    if ~isfile(objectiveFile)
        error('AllCueR2GaussianMeta:MissingObjective', ...
            'Saved all-cue objective not found: %s', objectiveFile);
    end
    loaded = load(objectiveFile, 'all_cue_r2_optimization');
    objective = loaded.all_cue_r2_optimization;
end
app = ExploreInteractiveGaussianMetaPopulation( ...
    CacheFile=options.CacheFile, MetricMode="SumFourCueR2", ...
    MetricPerCueR2=objective.CrossValidatedR2, ...
    SumFourCueR2=objective.SumFourCueCrossValidatedR2, ...
    ObjectiveLabel="Sum of four cue CV R^2: AI + AI:OD", ...
    InitialSigma=objective.BestSigma, ...
    Visible=options.Visible, Position=options.Position);
app.Objective = objective;
end
