function result = BuildAllCueOrdinaryR2GaussianMetaObjective(options)
%BUILDALLCUEORDINARYR2GAUSSIANMETAOBJECTIVE Sum four ordinary R-squared values.
%
% This deliberately simple objective performs no cross-validation. For
% every sigma and cue it uses the cached full-sample model:
%
%   DeltaBias = beta0 + beta1 * AI + beta2 * (AI .* OD)
%
% There is no standalone OD main effect. The selected sigma maximizes the
% unweighted sum of the four cue-specific ordinary R-squared values.

arguments
    options.CacheFile (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\MT\" + ...
        "GaussianMetaPopulationSigmaCache.mat"]
    options.OutputFolder (1, 1) string = ""
    options.UnitType (1, 1) string ...
        {mustBeMember(options.UnitType, ["2D", "3D"])} = "2D"
    options.FigureVisible (1, 1) logical = false
end

if ~isfile(options.CacheFile)
    error('AllCueOrdinaryR2GaussianMeta:MissingCache', ...
        'Gaussian-meta population cache not found: %s', options.CacheFile);
end
loaded = load(options.CacheFile, 'cache');
if ~isfield(loaded, 'cache') || ...
        ~isfield(loaded.cache, 'Statistics') || ...
        ~isfield(loaded.cache.Statistics, 'R2_AIxODWithinCondition')
    error('AllCueOrdinaryR2GaussianMeta:InvalidCache', ...
        'Cache does not contain per-cue AI + AI:OD ordinary R-squared.');
end
cache = loaded.cache;
if isfield(cache, 'ODDefinition')
    odDefinition = string(cache.ODDefinition);
else
    odDefinition = "Max";
end
commonFolder = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'common');
addpath(commonFolder);
selected = selectGaussianMetaUnitTypeData(cache, options.UnitType);
statistics = selected.Statistics;
if strlength(options.OutputFolder) == 0
    options.OutputFolder = fullfile(cache.OutputFolder, options.UnitType, ...
        'AllCueOrdinaryR2Optimization');
end
sigmaValues = double(cache.SigmaValues(:));
perCueR2 = double(statistics.R2_AIxODWithinCondition);
if ~isequal(size(perCueR2), [4 numel(sigmaValues)])
    error('AllCueOrdinaryR2GaussianMeta:InvalidR2Size', ...
        'Expected a 4-by-N per-cue R-squared matrix.');
end

validObjective = all(isfinite(perCueR2), 1);
sumFourCueR2 = sum(perCueR2, 1);
sumFourCueR2(~validObjective) = NaN;
validIndices = find(validObjective);
if isempty(validIndices)
    error('AllCueOrdinaryR2GaussianMeta:NoFiniteObjective', ...
        'No sigma has four finite per-cue ordinary R-squared values.');
end
[bestValue, relativeBest] = max(sumFourCueR2(validObjective));
bestIndex = validIndices(relativeBest);
bestSigma = sigmaValues(bestIndex);

objectiveTable = table(sigmaValues, perCueR2(1, :)', ...
    perCueR2(2, :)', perCueR2(3, :)', perCueR2(4, :)', ...
    sumFourCueR2', (sumFourCueR2 ./ 4)', ...
    statistics.N2DSessions(:), ...
    statistics.N3DSessions(:), ...
    statistics.NPoints(1, :)', ...
    statistics.NPoints(2, :)', ...
    statistics.NPoints(3, :)', ...
    statistics.NPoints(4, :)', ...
    'VariableNames', {'Sigma', 'R2_Dominant', 'R2_Combined', ...
    'R2_Stereo', 'R2_NonDominant', 'SumFourCueR2', ...
    'MeanFourCueR2', 'N2DSessions', 'N3DSessions', ...
    'N_Dominant', 'N_Combined', 'N_Stereo', 'N_NonDominant'});

ensureFolder(options.OutputFolder);
writetable(objectiveTable, fullfile(options.OutputFolder, ...
    'AllCueOrdinaryR2GaussianMetaObjective.csv'));

result = struct();
result.CacheFile = options.CacheFile;
result.OutputFolder = options.OutputFolder;
result.Area = selected.Area;
result.UnitType = options.UnitType;
result.ODDefinition = odDefinition;
result.ModelFormula = "DeltaBias ~ AI + AI:OD";
result.ObjectiveDefinition = ...
    "R2_Dominant + R2_Combined + R2_Stereo + R2_NonDominant";
result.SigmaValues = sigmaValues;
result.PerCueR2 = perCueR2;
result.SumFourCueR2 = sumFourCueR2(:);
result.BestIndex = bestIndex;
result.BestSigma = bestSigma;
result.BestSumFourCueR2 = bestValue;
result.BestMeanFourCueR2 = bestValue ./ 4;
result.BestPerCueR2 = perCueR2(:, bestIndex);
result.BestN2DSessions = statistics.N2DSessions(bestIndex);
result.BestN3DSessions = statistics.N3DSessions(bestIndex);
result.ObjectiveTable = objectiveTable;
all_cue_ordinary_r2_optimization = result;
save(fullfile(options.OutputFolder, ...
    'AllCueOrdinaryR2GaussianMetaOptimization.mat'), ...
    'all_cue_ordinary_r2_optimization', '-v7.3');

previousVisibility = get(groot, 'defaultFigureVisible');
visibilityCleanup = onCleanup( ...
    @() set(groot, 'defaultFigureVisible', previousVisibility));
set(groot, 'defaultFigureVisible', ...
    ternary(options.FigureVisible, 'on', 'off'));
figureHandle = figure('Color', 'w', ...
    'Name', 'All-cue ordinary-R2 Gaussian-meta objective', ...
    'Position', [120 120 980 650]);
hold on
conditionNames = ["Dominant", "Combined", "Stereo", "NonDominant"];
conditionColors = double(cache.ConditionColors);
for condition = 1:4
    plot(sigmaValues, perCueR2(condition, :), '-', ...
        'Color', conditionColors(condition, :), 'LineWidth', 1.2, ...
        'DisplayName', conditionNames(condition) + " R^2");
end
plot(sigmaValues, sumFourCueR2, 'k-', 'LineWidth', 3, ...
    'DisplayName', 'Sum of four ordinary R^2 values');
xline(bestSigma, 'r--', 'LineWidth', 2, ...
    'DisplayName', sprintf('Best sigma = %.6g', bestSigma));
plot(bestSigma, bestValue, 'ro', 'MarkerFaceColor', 'r', ...
    'MarkerSize', 8, 'HandleVisibility', 'off');
set(gca, 'XScale', 'log');
grid on; box on
xlabel('Gaussian \sigma');
ylabel('Ordinary population R^2 objective');
title(sprintf([ ...
    '%s %s four-cue ordinary R^2 sum (%s OD): ' ...
    'DeltaBias ~ AI + AI:OD'], ...
    result.Area, result.UnitType, result.ODDefinition));
subtitle(sprintf('Best sigma %.6g; summed R^2 %.4f; mean R^2 %.4f', ...
    bestSigma, bestValue, bestValue ./ 4));
legend('Location', 'best');
exportgraphics(figureHandle, fullfile(options.OutputFolder, ...
    'AllCueOrdinaryR2GaussianMetaObjective.png'), 'Resolution', 300);
savefig(figureHandle, fullfile(options.OutputFolder, ...
    'AllCueOrdinaryR2GaussianMetaObjective.fig'));
close(figureHandle);
clear visibilityCleanup

manifest = [ ...
    "All-cue ordinary-R-squared Gaussian-meta optimization"; ...
    "Area: " + result.Area; ...
    "Unit type: " + result.UnitType; ...
    "OD definition: " + result.ODDefinition; ...
    "No cross-validation"; ...
    "Model: " + result.ModelFormula; ...
    "Objective: " + result.ObjectiveDefinition; ...
    "Best sigma: " + bestSigma; ...
    "Best summed ordinary R-squared: " + bestValue; ...
    "Best mean ordinary R-squared: " + result.BestMeanFourCueR2; ...
    "Per-cue ordinary R-squared at optimum: " + ...
    join(compose('%.8g', result.BestPerCueR2), ", "); ...
    "Meta-classified sessions at optimum: " + ...
    selectedSessionCount(result, result.UnitType); ...
    "Source cache: " + options.CacheFile];
writelines(manifest, fullfile(options.OutputFolder, ...
    'AllCueOrdinaryR2GaussianMetaManifest.txt'));

fprintf(['All-cue ordinary-R2 optimum: sigma %.12g, sum %.8f, ' ...
    'mean %.8f, %s %s N=%d. Outputs: %s\n'], ...
    bestSigma, bestValue, bestValue ./ 4, ...
    result.Area, result.UnitType, ...
    selectedSessionCount(result, result.UnitType), options.OutputFolder);
end


function count = selectedSessionCount(result, unitType)
if unitType == "2D"
    count = result.BestN2DSessions;
else
    count = result.BestN3DSessions;
end
end


function ensureFolder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end


function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
