function app = ExploreInteractiveGaussianMetaPopulationAllCueOrdinaryR2(options)
%EXPLOREINTERACTIVEGAUSSIANMETAPOPULATIONALLCUEORDINARYR2 Launch simple R2 UI.

arguments
    options.CacheFile (1, 1) string = [ ...
        "C:\EM\CurrentSpread\02_gaussian\" + ...
        "InteractiveGaussianMetaPopulation\MT\" + ...
        "GaussianMetaPopulationSigmaCache.mat"]
    options.ObjectiveFolder (1, 1) string = ""
    options.UnitType (1, 1) string ...
        {mustBeMember(options.UnitType, ["2D", "3D"])} = "2D"
    options.Visible (1, 1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.Position (1, 4) double = [60 60 1540 900]
    options.SaveObjectiveResults (1, 1) logical = true
end

commonFolder = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'common');
addpath(commonFolder);
if strlength(options.ObjectiveFolder) == 0
    options.ObjectiveFolder = fullfile(fileparts(options.CacheFile), ...
        options.UnitType, 'AllCueOrdinaryR2Optimization');
end
if options.SaveObjectiveResults
    objective = BuildAllCueOrdinaryR2GaussianMetaObjective( ...
        CacheFile=options.CacheFile, UnitType=options.UnitType, ...
        OutputFolder=options.ObjectiveFolder);
else
    objectiveFile = fullfile(options.ObjectiveFolder, ...
        'AllCueOrdinaryR2GaussianMetaOptimization.mat');
    if ~isfile(objectiveFile)
        error('AllCueOrdinaryR2GaussianMeta:MissingObjective', ...
            'Saved ordinary-R2 objective not found: %s', objectiveFile);
    end
    loaded = load(objectiveFile, 'all_cue_ordinary_r2_optimization');
    objective = loaded.all_cue_ordinary_r2_optimization;
end

app = ExploreInteractiveGaussianMetaPopulation( ...
    CacheFile=options.CacheFile, UnitType=options.UnitType, ...
    MetricMode="SumFourCueOrdinaryR2", ...
    MetricPerCue=objective.PerCueR2, ...
    ObjectiveValues=objective.SumFourCueR2, ...
    ObjectiveLabel="Sum of four ordinary R^2: AI + AI:OD", ...
    InitialSigma=objective.BestSigma, ...
    Visible=options.Visible, Position=options.Position);
app.Objective = objective;
end
