function BatchResults = run_population_microsaccades_12ms_chunk(sessionRows, aggregateSuffix)
%RUN_POPULATION_MICROSACCADES_12MS_CHUNK Run a resumable 12 ms batch chunk.

unitTableFile = 'C:\EM\PopulationAnalysis\UnitTable_updating.mat';
outputRoot = 'C:\EM\Microsac\population_merged_12ms_no_smoothing';
directionFigureRoot = fullfile(outputRoot, 'figures', 'session_envelopes');
exampleFigureRoot = fullfile(outputRoot, 'figures', ...
    'session_random_trajectories');

BatchResults = run_population_microsaccade_analysis(unitTableFile, ...
    'OutputRoot', outputRoot, ...
    'AggregateSuffix', aggregateSuffix, ...
    'SessionRows', sessionRows, ...
    'SmoothWindowMs', 0, ...
    'MinDurationMs', 12, ...
    'RequireBinocular', false, ...
    'ComparisonPermutationCount', 1000, ...
    'SaveEyeTraces', false, ...
    'MakeQCPlot', true, ...
    'MakeDirectionPlot', true, ...
    'MakeExampleTrajectoryPlot', true, ...
    'ExampleTrajectoryCountPerCondition', 20, ...
    'DirectionFigureRoot', directionFigureRoot, ...
    'ExampleFigureRoot', exampleFigureRoot, ...
    'OverwriteExisting', false, ...
    'ContinueOnError', true);
end
