%% Trial-level MS prediction of choice for the completed 12 ms population batch
populationRoot = 'C:\EM\Microsac\population_merged_12ms_no_smoothing';

TrialwiseChoice = analyze_trialwise_ms_choice( ...
    'PopulationRoot', populationRoot, ...
    'ExpectedSmoothWindowMs', 0, ...
    'ExpectedMinDurationMs', 12, ...
    'ExpectedRequireBinocular', false, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'trialwise_ms_choice'));

