%% Overnight population microsaccade analysis
unitTableFile = 'C:\EM\PopulationAnalysis\UnitTable_updating.mat';
outputRoot = 'C:\EM\Microsac\population_merged_6ms_no_smoothing';

if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
completeMarker = fullfile(outputRoot, 'BATCH_COMPLETE.txt');
failureMarker = fullfile(outputRoot, 'BATCH_FATAL_ERROR.txt');

try
    BatchResults = run_population_microsaccade_analysis(unitTableFile, ...
        'OutputRoot', outputRoot, ...
        'SmoothWindowMs', 0, ...
        'MinDurationMs', 6, ...
        'RequireBinocular', false, ...
        'ComparisonPermutationCount', 1000, ...
        'SaveEyeTraces', false, ...
        'MakeQCPlot', true, ...
        'MakeDirectionPlot', true, ...
        'MakeExampleTrajectoryPlot', true, ...
        'ExampleTrajectoryCount', 10, ...
        'OverwriteExisting', false, ...
        'ContinueOnError', true);

    marker = fopen(completeMarker, 'w');
    cleanup = onCleanup(@() fclose(marker));
    fprintf(marker, 'Completed: %s\n', char(datetime('now')));
    fprintf(marker, 'Sessions in manifest: %d\n', height(BatchResults.SessionTable));
    fprintf(marker, 'Completed: %d\n', nnz(ismember( ...
        BatchResults.SessionTable.Status, ["Completed", "LoadedExisting"])));
    fprintf(marker, 'Failed: %d\n', nnz(BatchResults.SessionTable.Status == "Failed"));
    fprintf(marker, 'Skipped: %d\n', nnz(BatchResults.SessionTable.Status == "SkippedNoFiles"));
catch errorInfo
    marker = fopen(failureMarker, 'w');
    if marker >= 0
        fprintf(marker, 'Fatal error: %s\n\n%s\n', char(datetime('now')), ...
            getReport(errorInfo, 'extended', 'hyperlinks', 'off'));
        fclose(marker);
    end
    rethrow(errorInfo)
end
