%% Pool trial-level MS/choice data into Jim/Clay x MT/FST groups
populationRoot = 'C:\EM\Microsac\population_merged_12ms_no_smoothing';
trialwiseResultsFile = fullfile(populationRoot, 'population_analysis', ...
    'trialwise_ms_choice', 'trialwise_ms_choice_results.mat');

GroupedMSChoice = analyze_grouped_ms_choice( ...
    'TrialwiseResultsFile', trialwiseResultsFile, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice'));

GroupedSimpleScatter = plot_grouped_simple_ms_choice_scatter( ...
    'TrialwiseResultsFile', trialwiseResultsFile, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice', 'simple_scatter'));

GroupedProbabilityPlots = plot_grouped_ms_choice_probability( ...
    'TrialwiseResultsFile', trialwiseResultsFile, ...
    'GroupedResultsFile', GroupedMSChoice.OutputFiles.Mat, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice', 'probability_plots'));

PooledLogisticMSChoice = analyze_pooled_logistic_ms_choice( ...
    'TrialwiseResultsFile', trialwiseResultsFile, ...
    'GroupedResultsFile', GroupedMSChoice.OutputFiles.Mat, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice', 'pooled_logistic'));
