%% Example microsaccade analysis for the Clay FST session
tInfoFile = 'C:\EM\Microsac\Clay_FST_17Feb2026_3DMotionStim_MUA_TInfo.mat';
selIndexFile = 'C:\EM\Microsac\Clay_FST_17Feb2026_3DMotionStim_MUA_SelIndex.mat';
outputDir = fullfile(fileparts(mfilename('fullpath')), 'results_engbert');

Results = analyze_microsaccades(tInfoFile, selIndexFile, ...
    'OutputDir', outputDir, ...
    'SmoothWindowMs', 5, ...
    'VelocityThresholdLambda', 6, ...
    'MinDurationMs', 12, ...
    'MergeGapMs', 0, ...
    'MinAmplitudeDeg', 0, ...
    'MaxAmplitudeDeg', Inf, ...
    'MaxDurationMs', Inf, ...
    'MaxInterocularOnsetLagMs', Inf, ...
    'MaxDirectionDifferenceDeg', 180, ...
    'DirectionBinCount', 24, ...
    'DirectionEnvelopePercentile', 95, ...
    'ComparisonPermutationCount', 1000, ...
    'ComparisonSeed', 1729, ...
    'SaveEyeTraces', true, ...
    'MakeQCPlot', true, ...
    'MakeDirectionPlot', true);
