%% Exact pooled logistic model: Choice ~ MeanMSY_Z * StimCondition
populationRoot = 'C:\EM\Microsac\population_merged_12ms_no_smoothing';
trialwiseResultsFile = fullfile(populationRoot, 'population_analysis', ...
    'trialwise_ms_choice', 'trialwise_ms_choice_results.mat');
groupedResultsFile = fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice', 'grouped_ms_choice_results.mat');

PooledLogisticMSChoice = analyze_pooled_logistic_ms_choice( ...
    'TrialwiseResultsFile', trialwiseResultsFile, ...
    'GroupedResultsFile', groupedResultsFile, ...
    'OutputDir', fullfile(populationRoot, 'population_analysis', ...
    'grouped_monkey_roi_ms_choice', 'pooled_logistic'));
