%% Population figures and behavior models for the 12 ms detector
populationRoot = 'C:\EM\Microsac\population_merged_12ms_no_smoothing';
analysisRoot = fullfile(populationRoot, 'population_analysis');
directionStatsFile = fullfile(populationRoot, ...
    'population_microsaccade_direction_stats_complete.csv');
summaryFile = fullfile(populationRoot, ...
    'population_microsaccade_summary_complete.csv');

TrialwiseChoice = analyze_trialwise_ms_choice( ...
    'PopulationRoot', populationRoot, ...
    'ExpectedSmoothWindowMs', 0, ...
    'ExpectedMinDurationMs', 12, ...
    'ExpectedRequireBinocular', false, ...
    'OutputDir', fullfile(analysisRoot, 'trialwise_ms_choice'));

BehaviorMT = analyze_ms_behavior_bias( ...
    'MicrosaccadeStatsFile', directionStatsFile, ...
    'FilterROI', 'MT', ...
    'OutputDir', fullfile(analysisRoot, 'ms_y_bias_by_roi', 'MT'));
BehaviorFST = analyze_ms_behavior_bias( ...
    'MicrosaccadeStatsFile', directionStatsFile, ...
    'FilterROI', 'FST', ...
    'OutputDir', fullfile(analysisRoot, 'ms_y_bias_by_roi', 'FST'));

HistogramResults = plot_population_ms_metric_histograms( ...
    'DirectionStatsFile', directionStatsFile, ...
    'SummaryFile', summaryFile, ...
    'OutputDir', fullfile(analysisRoot, 'histograms'));

PairedResults = analyze_paired_ms_bias_lme( ...
    'LongTableFiles', {BehaviorMT.OutputFiles.LongTableCSV, ...
    BehaviorFST.OutputFiles.LongTableCSV}, ...
    'OutputDir', fullfile(analysisRoot, 'paired_ms_y_bias_lme'));

CenteredChangeResults = analyze_centered_ms_bias_changes( ...
    'LongTableFiles', {BehaviorMT.OutputFiles.LongTableCSV, ...
    BehaviorFST.OutputFiles.LongTableCSV}, ...
    'OutputDir', fullfile(analysisRoot, 'paired_ms_y_bias_lme', ...
    'centered_change'));

save(fullfile(analysisRoot, 'population_12ms_postprocessing_results.mat'), ...
    'TrialwiseChoice', 'BehaviorMT', 'BehaviorFST', 'HistogramResults', ...
    'PairedResults', 'CenteredChangeResults', '-v7.3');
