%% Smoke test the first resolvable UnitTable session
unitTableFile = 'C:\EM\PopulationAnalysis\UnitTable_updating.mat';
outputRoot = fullfile('C:\EM\Microsac', 'population_results_smoke');

BatchResults = run_population_microsaccade_analysis(unitTableFile, ...
    'OutputRoot', outputRoot, ...
    'MaxSessions', 1, ...
    'ComparisonPermutationCount', 1000, ...
    'SaveEyeTraces', false, ...
    'MakeQCPlot', true, ...
    'MakeDirectionPlot', true, ...
    'OverwriteExisting', false, ...
    'ContinueOnError', false);
