function cfg = ExampleNeuronPlotConfig()
%EXAMPLENEURONPLOTCONFIG Default configuration for example neuron exports.
% Edit cfg.examples to point at the recordings and units you want to plot.

cfg = struct();

% Repository location for shared analysis functions.
cfg.code_root = 'C:\Users\zzhu329\Documents\GitHub\EM-3DMotion\LoCodes';

% Shared MATLAB dependency roots required by Offline_3DMotion_update.
cfg.dependency_paths = { ...
    'P:\Codes\Matlab\offlineAnalysis'};

% Output folder for exported figures.
cfg.output_dir = 'C:\LoData\ExampleNeuronPlotScripts\Output';

% Prefer the saved MIDTable exported in OD_2D3DCompare.
% Set this to false only if you want to rebuild the table from source files.
cfg.use_saved_midtable = true;
cfg.midtable_path = ...
    'C:\Users\zzhu329\Documents\GitHub\EM-3DMotion\OD_2D3DCompare\AllMonkeyMIDTable.mat';

% Save options.
cfg.close_figures_after_save = true;
cfg.also_save_fig = false;

% Default examples copied from ExampleNeuronPlots.m.
cfg.examples = struct( ...
    'DisplayName', { ...
        'Jim_MT_30Apr2019_TT3_U2', ...
        'Jim_FST_15Sep2020_TT7_U5', ...
        'Clay_MT_29Apr2021_TT8_U2', ...
        'Clay_MT_04Jun2021_TT5_U2'}, ...
    'RecordingName', { ...
        'Jim_MT_30April2019_TT3_mrg_Sorted-02_3DMotion_TInfo.mat', ...
        'Jim_FST_15September2020_TT7_mrg_Sorted-02_3DMotion_TInfo.mat', ...
        'Clay_MT_29April2021_TT8_mrg_Sorted-04_3DMotion_TInfo.mat', ...
        'Clay_MT_04June2021_TT5_mrg_Sorted-01_3DMotion_TInfo.mat'}, ...
    'Unit', {2, 5, 2, 2});
end
