%% Export review plots for every Jim and Clay MUA-stimulation session
% The batch is resumable: existing PNGs are kept and recorded as Existing.

thisDirectory = fileparts(mfilename('fullpath'));
addpath(thisDirectory);

configs = struct( ...
    'Monkey', {'Jim', 'Clay'}, ...
    'Workbook', { ...
        'P:\Jim\NeuroData\RecordingRecord_Stimulation_final.xlsx', ...
        'P:\Clay\NeuroData\RecordingRecord_Stimulation.xlsx'}, ...
    'CacheDirectory', { ...
        'C:\Jim\StimData', ...
        'C:\Clay\StimData'});

outputDirectory = 'C:\EM\allSessions';
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

manifestPath = fullfile(outputDirectory, 'allSessions_manifest.csv');
manifest = emptyManifest();
sessionNumber = 0;

for iConfig = 1:numel(configs)
    config = configs(iConfig);
    if ~isfile(config.Workbook)
        warning('AllSessions:MissingWorkbook', ...
            'Workbook not found: %s', config.Workbook);
        continue
    end
    if ~isfolder(config.CacheDirectory)
        warning('AllSessions:MissingCacheDirectory', ...
            'Cache directory not found: %s', config.CacheDirectory);
        continue
    end

    recordingTable = readtable(config.Workbook, ...
        'VariableNamingRule', 'preserve');
    recordingDates = normalizeRecordingDates(recordingTable.Date);
    muaStim = strip(string(recordingTable.MUAStim));
    roi = strip(string(recordingTable.ROI));
    includedRows = find(strcmpi(muaStim, 'Y') & ...
        ismember(upper(roi), ["MT", "FST"]) & ~isnat(recordingDates));

    for iSession = 1:numel(includedRows)
        sessionNumber = sessionNumber + 1;
        workbookRow = includedRows(iSession);
        sessionDate = recordingDates(workbookRow);
        stimElectrode = double(recordingTable.StimElec(workbookRow));
        dateCode = string(sessionDate, 'yyyyMMdd');
        dateLabel = string(sessionDate, 'yyyy-MM-dd');
        cacheFile = fullfile(config.CacheDirectory, char(dateCode + ".mat"));
        expectedFile = fullfile(outputDirectory, sprintf( ...
            '%03d_%s_%s_%s_stim%02d.png', sessionNumber, ...
            config.Monkey, char(roi(workbookRow)), char(dateLabel), stimElectrode));
        existingFile = dir(expectedFile);
        if isempty(existingFile)
            legacyPattern = sprintf('*_%s_%s_%s_stim%02d.png', ...
                config.Monkey, char(roi(workbookRow)), char(dateLabel), stimElectrode);
            existingFile = dir(fullfile(outputDirectory, legacyPattern));
        end

        fprintf('[%d] %s %s (%s, stim %d)\n', sessionNumber, ...
            config.Monkey, char(dateCode), char(roi(workbookRow)), stimElectrode);

        if ~isempty(existingFile)
            pngPath = fullfile(existingFile(1).folder, existingFile(1).name);
            if ~strcmpi(pngPath, expectedFile)
                movefile(pngPath, expectedFile);
                pngPath = expectedFile;
            end
            manifest = appendManifestRow(manifest, sessionNumber, config, ...
                workbookRow, sessionDate, roi(workbookRow), stimElectrode, ...
                cacheFile, "Existing", "", pngPath);
            writetable(manifest, manifestPath);
            continue
        end

        if ~isfile(cacheFile)
            message = "Session cache is missing.";
            manifest = appendManifestRow(manifest, sessionNumber, config, ...
                workbookRow, sessionDate, roi(workbookRow), stimElectrode, ...
                cacheFile, "MissingCache", message, "");
            writetable(manifest, manifestPath);
            warning('AllSessions:MissingCache', '%s', cacheFile);
            continue
        end

        try
            plotManifest = PlotExampleSessions(cacheFile, ...
                OutputDirectory=outputDirectory, ...
                Formats="png", ...
                Visible="off", ...
                CloseFigures=true, ...
                WriteManifest=false, ...
                SessionNumber=sessionNumber, ...
                StimElectrode=stimElectrode, ...
                Monkey=config.Monkey, ...
                ROI=roi(workbookRow), ...
                SessionDate=sessionDate);
            manifest = appendManifestRow(manifest, sessionNumber, config, ...
                workbookRow, sessionDate, roi(workbookRow), stimElectrode, ...
                cacheFile, "Success", "", plotManifest.PNG(1));
        catch ME
            manifest = appendManifestRow(manifest, sessionNumber, config, ...
                workbookRow, sessionDate, roi(workbookRow), stimElectrode, ...
                cacheFile, "Failed", string(ME.message), "");
            warning('AllSessions:PlotFailed', '%s %s: %s', ...
                config.Monkey, char(dateCode), ME.message);
        end
        writetable(manifest, manifestPath);
    end
end

fprintf('Finished: %d successful, %d existing, %d missing, %d failed.\n', ...
    nnz(manifest.Status == "Success"), ...
    nnz(manifest.Status == "Existing"), ...
    nnz(manifest.Status == "MissingCache"), ...
    nnz(manifest.Status == "Failed"));
fprintf('Plots and manifest: %s\n', outputDirectory);

function manifest = emptyManifest()
manifest = table('Size', [0 12], ...
    'VariableTypes', {'double','string','double','datetime','string', ...
        'double','string','string','string','string','string','string'}, ...
    'VariableNames', {'SessionNumber','Monkey','WorkbookRow','Date','ROI', ...
        'StimElectrode','Workbook','CacheFile','Status','Message','PNG', ...
        'GeneratedAt'});
end

function manifest = appendManifestRow(manifest, sessionNumber, config, ...
        workbookRow, sessionDate, roi, stimElectrode, cacheFile, status, ...
        message, pngPath)
newRow = table(sessionNumber, string(config.Monkey), workbookRow + 1, ...
    sessionDate, string(roi), stimElectrode, string(config.Workbook), ...
    string(cacheFile), string(status), string(message), string(pngPath), ...
    string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')), ...
    'VariableNames', manifest.Properties.VariableNames);
manifest = [manifest; newRow];
end

function dates = normalizeRecordingDates(values)
if isdatetime(values)
    dates = values;
elseif isnumeric(values)
    dates = datetime(values, 'ConvertFrom', 'excel');
elseif iscell(values)
    dates = datetime(string(values));
else
    dates = datetime(values);
end
dates = dates(:);
end
