function suite = BuildInteractiveGaussianMetaPopulationSuite(options)
%BUILDINTERACTIVEGAUSSIANMETAPOPULATIONSUITE Build all cached objectives.
%
% Builds one area- and OD-definition-specific 1000-sigma cache and the CV AI+AI:OD,
% ordinary AI+AI:OD, and Type-II distance objectives for meta-derived 2D
% and 3D sessions. It also fits the channel-first behavioral prediction
% model, where beta is applied per channel before Gaussian aggregation.
% Generated artifacts remain under C:\EM by default.

arguments
    options.Area (1, 1) string ...
        {mustBeMember(options.Area, ["MT", "FST"])} = "MT"
    options.ODDefinition (1, 1) string ...
        {mustBeMember(options.ODDefinition, ...
        ["Max", "RMSE", "Correlation", "PartialCorrelation"])} = "Max"
    options.OutputRoot (1, 1) string = ""
    options.StateFile (1, 1) string = ...
        "C:\EM\BehaviorFitting\unit_table_gof.mat"
    options.Monkey (1, 1) string ...
        {mustBeMember(options.Monkey, ["Both", "Jim", "Clay"])} = "Both"
    options.SigmaValues (1, :) double = logspace(-2, 2, 1000)
    options.ValidateAgainstBuilder (1, 1) logical = true
    options.FigureVisible (1, 1) logical = false
    options.StimChannelReferenceSigma (1, 1) double ...
        {mustBePositive} = 0.01
    options.RefreshFromWorkbooks (1, 1) logical = false
end

interactiveRoot = string(fileparts(mfilename('fullpath')));
commonFolder = fullfile(interactiveRoot, 'common');
cvFolder = fullfile(interactiveRoot, 'cv_ai_od');
ordinaryFolder = fullfile(interactiveRoot, 'ordinary_ai_od');
distanceFolder = fullfile(interactiveRoot, 'type2_distance');
channelPredictionFolder = fullfile(interactiveRoot, 'channel_prediction');
addpath(commonFolder, cvFolder, ordinaryFolder, distanceFolder, ...
    channelPredictionFolder);

if strlength(options.OutputRoot) == 0
    outputRoot = ...
        "C:\EM\CurrentSpread\02_gaussian\InteractiveGaussianMetaPopulation";
    if options.ODDefinition ~= "Max"
        folderName = options.ODDefinition + "OD";
        outputRoot = fullfile(outputRoot, folderName);
    end
    options.OutputRoot = fullfile(outputRoot, options.Area);
end

cache = BuildInteractiveGaussianMetaPopulationCache( ...
    Area=options.Area, OutputFolder=options.OutputRoot, ...
    StateFile=options.StateFile, Monkey=options.Monkey, ...
    ODDefinition=options.ODDefinition, ...
    SigmaValues=options.SigmaValues, ...
    StimChannelReferenceSigma=options.StimChannelReferenceSigma, ...
    RefreshFromWorkbooks=options.RefreshFromWorkbooks, ...
    ValidateAgainstBuilder=options.ValidateAgainstBuilder);
cacheFile = fullfile(options.OutputRoot, ...
    'GaussianMetaPopulationSigmaCache.mat');

unitTypes = ["2D", "3D"];
cvResults = struct();
ordinaryResults = struct();
distanceResults = struct();
channelPredictionResults = struct();
summary = table();
for unitType = unitTypes
    fieldName = char("Meta" + unitType);
    cv = BuildAllCueR2GaussianMetaObjective( ...
        CacheFile=cacheFile, UnitType=unitType, ...
        FigureVisible=options.FigureVisible);
    ordinary = BuildAllCueOrdinaryR2GaussianMetaObjective( ...
        CacheFile=cacheFile, UnitType=unitType, ...
        FigureVisible=options.FigureVisible);
    distance = BuildAllCueType2DistanceGaussianMetaObjective( ...
        CacheFile=cacheFile, UnitType=unitType, ...
        FigureVisible=options.FigureVisible);
    channelPrediction = BuildGaussianChannelBiasPredictionObjective( ...
        CacheFile=cacheFile, UnitType=unitType, ...
        FigureVisible=options.FigureVisible);
    cvResults.(fieldName) = cv;
    ordinaryResults.(fieldName) = ordinary;
    distanceResults.(fieldName) = distance;
    channelPredictionResults.(fieldName) = channelPrediction;

    cvCount = selectedSessionCount(cache, unitType, cv.BestIndex);
    ordinaryCount = selectedSessionCount( ...
        cache, unitType, ordinary.BestIndex);
    distanceCount = selectedSessionCount( ...
        cache, unitType, distance.BestIndex);
    summary = [summary; table(options.Area, options.ODDefinition, unitType, ...
        repmat("CV AI + AI:OD", 1, 1), cv.BestSigma, ...
        cv.BestSumFourCueCrossValidatedR2, cvCount, ...
        'VariableNames', {'Area', 'ODDefinition', 'UnitType', 'Method', 'BestSigma', ...
        'ObjectiveValue', 'SelectedSessionCount'}); ...
        table(options.Area, options.ODDefinition, unitType, ...
        repmat("Channel-first ordinary R2 (Dom AI x |OD|)", 1, 1), ...
        channelPrediction.BestSigma, channelPrediction.BestSumFourCueOrdinaryR2, ...
        channelPrediction.SessionCount, ...
        'VariableNames', {'Area', 'ODDefinition', 'UnitType', 'Method', 'BestSigma', ...
        'ObjectiveValue', 'SelectedSessionCount'}); ...
        table(options.Area, options.ODDefinition, unitType, ...
        repmat("Ordinary AI + AI:OD", 1, 1), ...
        ordinary.BestSigma, ordinary.BestSumFourCueR2, ordinaryCount, ...
        'VariableNames', {'Area', 'ODDefinition', 'UnitType', 'Method', 'BestSigma', ...
        'ObjectiveValue', 'SelectedSessionCount'}); ...
        table(options.Area, options.ODDefinition, unitType, ...
        repmat("Type II distance", 1, 1), ...
        distance.BestSigma, distance.BestSumFourCueMeanSquaredDistance, ...
        distanceCount, 'VariableNames', {'Area', 'ODDefinition', ...
        'UnitType', 'Method', ...
        'BestSigma', 'ObjectiveValue', 'SelectedSessionCount'})]; %#ok<AGROW>
end

writetable(summary, fullfile(options.OutputRoot, ...
    'GaussianMetaPopulationSuiteSummary.csv'));
suite = struct();
suite.Area = options.Area;
suite.ODDefinition = options.ODDefinition;
suite.OutputRoot = options.OutputRoot;
suite.CacheFile = cacheFile;
suite.Cache = cache;
suite.CV = cvResults;
suite.Ordinary = ordinaryResults;
suite.Type2Distance = distanceResults;
suite.ChannelPrediction = channelPredictionResults;
suite.Summary = summary;
gaussian_meta_population_suite = suite;
save(fullfile(options.OutputRoot, ...
    'GaussianMetaPopulationSuite.mat'), ...
    'gaussian_meta_population_suite', '-v7.3');

fprintf('Completed %s %s-OD Gaussian-meta 2D/3D suite: %s\n', ...
    options.Area, options.ODDefinition, options.OutputRoot);
end


function count = selectedSessionCount(cache, unitType, sigmaIndex)
if unitType == "2D"
    count = cache.Statistics2D.N2DSessions(sigmaIndex);
else
    count = cache.Statistics3D.N3DSessions(sigmaIndex);
end
end
